### ISSUE TITLE
v12.10.0 brings in nrwl/cli@13.10 which causes install to fail

### ISSUE THREAD

**Issue by willyboy** [nrwl/nx#9755]
## Current Behavior

This is a multi-tiered problem.

When installing version 12.10 of NX, it has a nrwl/cli dependency of *. This means it brings in v13.10.0 of nrwl/cli.
https://github.com/nrwl/nx/blob/12.10.x/packages/nx/package.json

v13.10 of nrwl/cli has a code dependency on tar-stream but it is not declared in package.json
https://github.com/nrwl/nx/blob/13.10.0/packages/cli/package.json

nx v12.10.0 does not declare tar-stream in its package.json but nx v13.10.0 does. So for an nx v13 user this isn't an issue but for a v12 user, it results in a "module not found" error.

## Expected Behavior

1) nrwl/cli in package.json should not be set to "*". It should use the corresponding version. So nx@12 should use cli@12. 
2) cli@13 needs to declare tar-stream as a dependency in its package.sjon

Yes, this worked until 13.10 was released.

## Steps to Reproduce

Install nx v12 in your repo and the npm install will fail with "tar-stream module not found"

### Failure Logs

Error: Cannot find module 'tar-stream'
11:10:45  Require stack:
11:10:45  - /node_modules/nx/node_modules/@nrwl/tao/node_modules/nx/src/utils/fileutils.js
11:10:45  - /node_modules/nx/node_modules/@nrwl/tao/node_modules/nx/src/utils/cache-directory.js
11:10:45  - /node_modules/nx/node_modules/@nrwl/tao/node_modules/nx/src/project-graph/nx-deps-cache.js
11:10:45  - /node_modules/nx/node_modules/@nrwl/tao/node_modules/nx/src/project-graph/project-graph.js
11:10:45  - /node_modules/nx/node_modules/@nrwl/tao/node_modules/nx/bin/init.js
11:10:45      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
### Environment

Node : 14.17.5
  OS   : darwin x64
  npm  : 6.14.14
  
  nx : 12.10.0
  @nrwl/angular : 12.10.0
  @nrwl/cli : 12.10.0
  @nrwl/cypress : 12.10.0
  @nrwl/devkit : 12.10.0
  @nrwl/eslint-plugin-nx : 12.10.0
  @nrwl/express : 12.10.0
  @nrwl/jest : 12.10.0
  @nrwl/linter : 12.10.0
  @nrwl/nest : 12.10.0
  @nrwl/next : Not Found
  @nrwl/node : 12.10.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.0
  @nrwl/storybook : 12.10.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by gioragutt** [comment]
Just FYI, the version of all `@nrwl/` dependencies in `package.json` of `@nrwl/` packages is `*` because it gets replaced by the release pipeline with the latest version.

However, in this case, I think that you should remove the `nx` package from your dependencies. Until recently, I'm not sure `nx` was meant to be installed as a dependency in `package.json`.

I took a look at the output of `npm view nx@12.10 dependencies devDependencies` and got the following output:

```
nx@12.10.0 { '@nrwl/cli': '*' }
nx@12.10.1 { '@nrwl/cli': '*' }
```

Which is exactly what you said. I took it further and did the search for `@12` and `@13`:

<details>
<summary>`@12`</summary>

```
nx@12.0.0 { '@nrwl/cli': '*' }
nx@12.0.1 { '@nrwl/cli': '*' }
nx@12.0.2 { '@nrwl/cli': '*' }
nx@12.0.3 { '@nrwl/cli': '*' }
nx@12.0.4 { '@nrwl/cli': '*' }
nx@12.0.5 { '@nrwl/cli': '*' }
nx@12.0.6 { '@nrwl/cli': '*' }
nx@12.0.7 { '@nrwl/cli': '*' }
nx@12.0.8 { '@nrwl/cli': '*' }
nx@12.1.0 { '@nrwl/cli': '*' }
nx@12.1.1 { '@nrwl/cli': '*' }
nx@12.2.0 { '@nrwl/cli': '*' }
nx@12.3.0 { '@nrwl/cli': '*' }
nx@12.3.1 { '@nrwl/cli': '*' }
nx@12.3.2 { '@nrwl/cli': '*' }
nx@12.3.3 { '@nrwl/cli': '*' }
nx@12.3.4 { '@nrwl/cli': '*' }
nx@12.3.5 { '@nrwl/cli': '*' }
nx@12.3.6 { '@nrwl/cli': '*' }
nx@12.4.0 { '@nrwl/cli': '*' }
nx@12.5.0 { '@nrwl/cli': '*' }
nx@12.5.1 { '@nrwl/cli': '*' }
nx@12.5.2 { '@nrwl/cli': '*' }
nx@12.5.3 { '@nrwl/cli': '*' }
nx@12.5.4 { '@nrwl/cli': '*' }
nx@12.5.5 { '@nrwl/cli': '*' }
nx@12.5.6 { '@nrwl/cli': '*' }
nx@12.5.7 { '@nrwl/cli': '*' }
nx@12.5.8 { '@nrwl/cli': '*' }
nx@12.5.9 { '@nrwl/cli': '*' }
nx@12.6.0 { '@nrwl/cli': '*' }
nx@12.6.1 { '@nrwl/cli': '*' }
nx@12.6.2 { '@nrwl/cli': '*' }
nx@12.6.3 { '@nrwl/cli': '*' }
nx@12.6.4 { '@nrwl/cli': '*' }
nx@12.6.5 { '@nrwl/cli': '*' }
nx@12.6.6 { '@nrwl/cli': '*' }
nx@12.7.0 { '@nrwl/cli': '*' }
nx@12.7.1 { '@nrwl/cli': '*' }
nx@12.7.2 { '@nrwl/cli': '*' }
nx@12.8.0 { '@nrwl/cli': '*' }
nx@12.9.0 { '@nrwl/cli': '*' }
nx@12.10.0 { '@nrwl/cli': '*' }
nx@12.10.1 { '@nrwl/cli': '*' }
```
</details>

<details>
<summary>`@13`</summary>

```
nx@13.0.0 { '@nrwl/cli': '*' }
nx@13.0.1 { '@nrwl/cli': '*' }
nx@13.0.2 { '@nrwl/cli': '*' }
nx@13.1.0 { '@nrwl/cli': '*' }
nx@13.1.1 { '@nrwl/cli': '*' }
nx@13.1.2 { '@nrwl/cli': '*' }
nx@13.1.3 { '@nrwl/cli': '*' }
nx@13.1.4 { '@nrwl/cli': '*' }
nx@13.2.0 { '@nrwl/cli': '*' }
nx@13.2.1 { '@nrwl/cli': '*' }
nx@13.2.2 { '@nrwl/cli': '*' }
nx@13.2.3 { '@nrwl/cli': '*' }
nx@13.2.4 { '@nrwl/cli': '*' }
nx@13.3.0 { '@nrwl/cli': '13.3.0' }
nx@13.3.1 { '@nrwl/cli': '13.3.1' }
nx@13.3.2 { '@nrwl/cli': '13.3.2' }
nx@13.3.4 { '@nrwl/cli': '13.3.4' }
nx@13.3.5 { '@nrwl/cli': '13.3.5' }
nx@13.3.6 { '@nrwl/cli': '13.3.6' }
nx@13.3.7 { '@nrwl/cli': '13.3.7' }
nx@13.3.8 { '@nrwl/cli': '13.3.8' }
nx@13.3.9 { '@nrwl/cli': '13.3.9' }
nx@13.3.11 { '@nrwl/cli': '13.3.11' }
nx@13.3.12 { '@nrwl/cli': '13.3.12' }
nx@13.4.0 { '@nrwl/cli': '13.4.0' }
nx@13.4.1 { '@nrwl/cli': '13.4.1' }
nx@13.4.2 { '@nrwl/cli': '13.4.2' }
nx@13.4.3 { '@nrwl/cli': '13.4.3' }
nx@13.4.4 { '@nrwl/cli': '13.4.4' }
nx@13.4.5 { '@nrwl/cli': '13.4.5' }
nx@13.4.6 { '@nrwl/cli': '13.4.6' }
nx@13.5.0 { '@nrwl/cli': '13.5.0' }
nx@13.5.1 { '@nrwl/cli': '13.5.1' }
nx@13.1.5 { '@nrwl/cli': '*' }
nx@13.5.2 { '@nrwl/cli': '13.5.2' }
nx@13.5.3 { '@nrwl/cli': '13.5.3' }
nx@13.6.0 { '@nrwl/cli': '13.6.0' }
nx@13.6.1 { '@nrwl/cli': '13.6.1' }
nx@13.7.0 { '@nrwl/cli': '13.7.0' }
nx@13.7.1 { '@nrwl/cli': '13.7.1' }
nx@13.7.2 { '@nrwl/cli': '13.7.2' }
nx@13.7.3 { '@nrwl/cli': '13.7.3' }
nx@13.8.0 { '@nrwl/cli': '13.8.0' }
nx@13.8.1 { '@nrwl/cli': '13.8.1' }
nx@13.8.2 { '@nrwl/cli': '13.8.2' }
nx@13.8.3 { '@nrwl/cli': '13.8.3' }
nx@13.8.4 { '@nrwl/cli': '13.8.4' }
nx@13.8.5 { '@nrwl/cli': '13.8.5' }
nx@13.8.6 { '@nrwl/cli': '13.8.6' }
nx@13.8.7 { '@nrwl/cli': '13.8.7' }
nx@13.8.8 { '@nrwl/cli': '13.8.8' }
nx@13.1.6 { '@nrwl/cli': '*' }
nx@13.9.0 {
  '@swc/core': '^1.2.146',
  '@swc-node/register': '^1.4.2',
  chalk: '4.1.0',
  enquirer: '~2.3.6',
  'fast-glob': '3.2.7',
  'fs-extra': '^9.1.0',
  ignore: '^5.0.4',
  'jsonc-parser': '3.0.0',
  'rxjs-for-await': '0.0.2',
  rxjs: '^6.5.4',
  semver: '7.3.4',
  tmp: '~0.2.1',
  tslib: '^2.3.0',
  'tsconfig-paths': '^3.9.0',
  'yargs-parser': '20.0.0',
  'v8-compile-cache': '2.3.0',
  '@nrwl/cli': '13.9.0',
  '@nrwl/tao': '13.9.0'
}
nx@13.9.1 {
  '@swc/core': '^1.2.146',
  '@swc-node/register': '^1.4.2',
  chalk: '4.1.0',
  enquirer: '~2.3.6',
  'fast-glob': '3.2.7',
  'fs-extra': '^9.1.0',
  ignore: '^5.0.4',
  'jsonc-parser': '3.0.0',
  'rxjs-for-await': '0.0.2',
  rxjs: '^6.5.4',
  semver: '7.3.4',
  tmp: '~0.2.1',
  tslib: '^2.3.0',
  'tsconfig-paths': '^3.9.0',
  'yargs-parser': '20.0.0',
  'v8-compile-cache': '2.3.0',
  '@nrwl/cli': '13.9.1',
  '@nrwl/tao': '13.9.1'
}
nx@13.9.2 {
  '@swc/core': '^1.2.146',
  '@swc-node/register': '^1.4.2',
  chalk: '4.1.0',
  enquirer: '~2.3.6',
  'fast-glob': '3.2.7',
  'fs-extra': '^9.1.0',
  ignore: '^5.0.4',
  'jsonc-parser': '3.0.0',
  'rxjs-for-await': '0.0.2',
  rxjs: '^6.5.4',
  semver: '7.3.4',
  tmp: '~0.2.1',
  tslib: '^2.3.0',
  'tsconfig-paths': '^3.9.0',
  'yargs-parser': '20.0.0',
  'v8-compile-cache': '2.3.0',
  '@nrwl/cli': '13.9.2',
  '@nrwl/tao': '13.9.2'
}
nx@13.9.3 {
  '@swc/core': '^1.2.146',
  '@swc-node/register': '^1.4.2',
  chalk: '4.1.0',
  enquirer: '~2.3.6',
  'fast-glob': '3.2.7',
  'fs-extra': '^9.1.0',
  ignore: '^5.0.4',
  'jsonc-parser': '3.0.0',
  'rxjs-for-await': '0.0.2',
  rxjs: '^6.5.4',
  semver: '7.3.4',
  tmp: '~0.2.1',
  tslib: '^2.3.0',
  'tsconfig-paths': '^3.9.0',
  'yargs-parser': '20.0.0',
  'v8-compile-cache': '2.3.0',
  '@nrwl/cli': '13.9.3',
  '@nrwl/tao': '13.9.3'
}
nx@13.9.4 {
  '@swc/core': '^1.2.146',
  '@swc-node/register': '^1.4.2',
  chalk: '4.1.0',
  enquirer: '~2.3.6',
  'fast-glob': '3.2.7',
  'fs-extra': '^9.1.0',
  ignore: '^5.0.4',
  'jsonc-parser': '3.0.0',
  'rxjs-for-await': '0.0.2',
  rxjs: '^6.5.4',
  semver: '7.3.4',
  tmp: '~0.2.1',
  tslib: '^2.3.0',
  'tsconfig-paths': '^3.9.0',
  'yargs-parser': '20.0.0',
  'v8-compile-cache': '2.3.0',
  '@nrwl/cli': '13.9.4',
  '@nrwl/tao': '13.9.4'
}
nx@13.9.5 {
  '@swc/core': '^1.2.146',
  '@swc-node/register': '^1.4.2',
  chalk: '4.1.0',
  enquirer: '~2.3.6',
  'fast-glob': '3.2.7',
  'fs-extra': '^9.1.0',
  ignore: '^5.0.4',
  'jsonc-parser': '3.0.0',
  'rxjs-for-await': '0.0.2',
  rxjs: '^6.5.4',
  semver: '7.3.4',
  tmp: '~0.2.1',
  tslib: '^2.3.0',
  'tsconfig-paths': '^3.9.0',
  'yargs-parser': '20.0.0',
  'v8-compile-cache': '2.3.0',
  '@nrwl/cli': '13.9.5',
  '@nrwl/tao': '13.9.5'
}
nx@13.9.6 {
  '@swc/core': '^1.2.146',
  '@swc-node/register': '^1.4.2',
  chalk: '4.1.0',
  enquirer: '~2.3.6',
  'fast-glob': '3.2.7',
  'fs-extra': '^9.1.0',
  ignore: '^5.0.4',
  'jsonc-parser': '3.0.0',
  'rxjs-for-await': '0.0.2',
  rxjs: '^6.5.4',
  semver: '7.3.4',
  tmp: '~0.2.1',
  tslib: '^2.3.0',
  'tsconfig-paths': '^3.9.0',
  'yargs-parser': '20.0.0',
  'v8-compile-cache': '2.3.0',
  '@nrwl/cli': '13.9.6',
  '@nrwl/tao': '13.9.6'
}
nx@13.9.7 {
  '@swc/core': '^1.2.146',
  '@swc-node/register': '^1.4.2',
  chalk: '4.1.0',
  enquirer: '~2.3.6',
  'fast-glob': '3.2.7',
  'fs-extra': '^9.1.0',
  ignore: '^5.0.4',
  'jsonc-parser': '3.0.0',
  'rxjs-for-await': '0.0.2',
  rxjs: '^6.5.4',
  semver: '7.3.4',
  tmp: '~0.2.1',
  tslib: '^2.3.0',
  'tsconfig-paths': '^3.9.0',
  'yargs-parser': '20.0.0',
  'v8-compile-cache': '2.3.0',
  '@nrwl/cli': '13.9.7',
  '@nrwl/tao': '13.9.7'
}
nx@13.10.0 {
  '@swc/core': '^1.2.152',
  '@swc-node/register': '^1.4.2',
  'fast-glob': '3.2.7',
  'jsonc-parser': '3.0.0',
  'rxjs-for-await': '0.0.2',
  'tsconfig-paths': '^3.9.0',
  'v8-compile-cache': '2.3.0',
  '@parcel/watcher': '2.0.4',
  chokidar: '^3.5.1',
  'cli-cursor': '3.1.0',
  'cli-spinners': '2.6.1',
  'fs-extra': '^9.1.0',
  dotenv: '~10.0.0',
  figures: '3.2.0',
  glob: '7.1.4',
  ignore: '^5.0.4',
  'npm-run-path': '^4.0.1',
  open: '^8.4.0',
  rxjs: '^6.5.4',
  semver: '7.3.4',
  'tar-stream': '~2.2.0',
  tmp: '~0.2.1',
  yargs: '^17.4.0',
  'yargs-parser': '21.0.1',
  chalk: '4.1.0',
  flat: '^5.0.2',
  minimatch: '3.0.4',
  enquirer: '~2.3.6',
  tslib: '^2.3.0',
  '@nrwl/cli': '13.10.0',
  '@nrwl/tao': '13.10.0'
}
nx@13.10.1 {
  '@swc/core': '^1.2.152',
  '@swc-node/register': '^1.4.2',
  'fast-glob': '3.2.7',
  'jsonc-parser': '3.0.0',
  'rxjs-for-await': '0.0.2',
  'tsconfig-paths': '^3.9.0',
  'v8-compile-cache': '2.3.0',
  '@parcel/watcher': '2.0.4',
  chokidar: '^3.5.1',
  'cli-cursor': '3.1.0',
  'cli-spinners': '2.6.1',
  'fs-extra': '^9.1.0',
  dotenv: '~10.0.0',
  figures: '3.2.0',
  glob: '7.1.4',
  ignore: '^5.0.4',
  'npm-run-path': '^4.0.1',
  open: '^8.4.0',
  rxjs: '^6.5.4',
  semver: '7.3.4',
  'tar-stream': '~2.2.0',
  tmp: '~0.2.1',
  yargs: '^17.4.0',
  'yargs-parser': '21.0.1',
  chalk: '4.1.0',
  flat: '^5.0.2',
  minimatch: '3.0.4',
  enquirer: '~2.3.6',
  tslib: '^2.3.0',
  '@nrwl/cli': '13.10.1',
  '@nrwl/tao': '13.10.1'
}
```
</details>

What we can see from this output is that only starting `nx@13.3.0 { '@nrwl/cli': '13.3.0' }` the `nx` package had valid dependencies.

So for now, my suggestion is to remove `"nx"` itself from your dependencies.

**Comment by gioragutt** [comment]
Might I ask how you got `"nx"` dependency in your `package.json` with a v12 nx workspace? IIRC, it wasn't added by anything (any generators) at that time.

**Comment by willyboy** [comment]
> Might I ask how you got `"nx"` dependency in your `package.json` with a v12 nx workspace? IIRC, it wasn't added by anything (any generators) at that time.

We don't have "nx" as a dependency in package.json

**Comment by willyboy** [comment]
I should say, I was using NX as a broad term to refer to the NX tooling, not a specific package.

**Comment by willyboy** [comment]
@gioragutt Here's the dependency tree:
└─┬ @nrwl/tao@12.10.0
  └─┬ nx@12.10.0 
    └─┬ @nrwl/cli@13.10.0
      └── UNMET DEPENDENCY nx@13.10.0

**Comment by willyboy** [comment]
For anyone else experiencing this, workaround is to add an optional dependency in package.json. It seems to override the nested dep
```
"optionalDependencies": {
    "@nrwl/cli": "13.7.1",
```

**Comment by luke-rogers** [comment]
Can confirm I am also running into this when trying to create a new v12 workspace using
`npx create-nx-workspace@12.10.1 <org name> --preset=angular`

Not quite sure of the workaround this when creating a new workspace yet though...

**Comment by luke-rogers** [comment]
Seems like a possible workaround to issues with the above are to split the creation of the workspace into 2 phases

1. Create empty workspace - `npx create-nx-workspace@12.10.1 <org name>`
2. Add the dependency on @nwrl/angular - `npm i @nrwl/angular@12.10.1`
3. Create the angular project - `nx g @nrwl/angular:app <app name>`

Hoping nothing would be missed versus using `npx create-nx-workspace@12.10.1 <org name> --preset=angular` directly if it worked.

**Comment by FrozenPandaz** [comment]
yes, you are right, `12.10.1` was broken. At this point, we're on `v14` so I don't think we'll be publishing any more v12 versions. 

Sorry we didn't see this sooner but I believe this is no longer an issue in later versions of Nx. If you experience this issue with more recent versions of nx, please open a new issue.
