### ISSUE TITLE
Better error message when nx.json isn't found

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [nrwl/nx#9759]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
When you run `nx` in a directory that doesn't have an `'nx.json'`, the error message is a little... unpolished.

```plaintext
$ npx nx generate-lib @typescript-eslint/scope-manager
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'nx.json'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at OutputObfuscator.loadSecretKeys (/home/josh/repos/typescript-eslint/node_modules/@nrwl/nx-cloud/lib/core/terminal-output/output-obfuscator.js:49:97)
    at new OutputObfuscator (/home/josh/repos/typescript-eslint/node_modules/@nrwl/nx-cloud/lib/core/terminal-output/output-obfuscator.js:9:38)
    at cloudEnabledTasksRunner (/home/josh/repos/typescript-eslint/node_modules/@nrwl/nx-cloud/lib/core/runners/cloud-enabled/cloud-enabled.runner.js:1:6534)
    at nxCloudTasksRunner (/home/josh/repos/typescript-eslint/node_modules/@nrwl/nx-cloud/lib/nx-cloud-tasks-runner.js:51:63)
    at /home/josh/repos/typescript-eslint/node_modules/@nrwl/workspace/src/tasks-runner/run-command.js:85:37
    at Generator.next (<anonymous>)
    at fulfilled (/home/josh/repos/typescript-eslint/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'nx.json'
}
```

## Motivation
It's common for users to not realize which path they're running the command from. Not being able to find `'nx.json'` could be very confusing for them.

## Suggested Implementation
How about this error message by default:

```plaintext
$ npx nx command package-name
Error: could not find 'nx.json' file in current directory (/your/current/directory).
```

...and also check for one in a parent directory, for the common case of running a command within a packages dir by accident?

```plaintext
$ npx nx command package-name
Error: could not find 'nx.json' file in current directory (/parent/child/directory).
    👉 Tip: one was found in /parent; did you mean to run nx from that directory?
```

## Alternate Implementations
🤷

**Comment by StalkAltan** [comment]
No @nrwl/nx-cloud commands should assume they are being invoked from workspace root as of v14.0.5, closing this now.

**Comment by nhhockeyplayer** [comment]
is there reason why I am receiving this?

Run npx nx-cloud stop-all-agents
  npx nx-cloud stop-all-agents
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
    NX_BRANCH: main
    NX_CLOUD_ACCESS_TOKEN: 
    NX_CLOUD_AUTH_TOKEN: 
    NX_BASE: a45deaa0176c736ed[2](https://github.com/nhhockeyplayer/meanstacknh/runs/7265009429?check_suite_focus=true#step:23:2)[3](https://github.com/nhhockeyplayer/meanstacknh/runs/7265009429?check_suite_focus=true#step:23:3)5c[4](https://github.com/nhhockeyplayer/meanstacknh/runs/7265009429?check_suite_focus=true#step:23:4)27864[5](https://github.com/nhhockeyplayer/meanstacknh/runs/7265009429?check_suite_focus=true#step:23:5)b95f4d31b498
    NX_HEAD: 3e9[6](https://github.com/nhhockeyplayer/meanstacknh/runs/7265009429?check_suite_focus=true#step:23:6)a81[7](https://github.com/nhhockeyplayer/meanstacknh/runs/7265009429?check_suite_focus=true#step:23:7)43936779ec7cdba266c[8](https://github.com/nhhockeyplayer/meanstacknh/runs/7265009429?check_suite_focus=true#step:23:8)7dc35c2843f2
    VOLTA_HOME: /opt/hostedtoolcache/volta/1.0.8/x64
npm WARN exec The following package was not found and will be installed: nx-cloud
sh: 1: nx-cloud: not found
Error: Process completed with exit code [12](https://github.com/nhhockeyplayer/meanstacknh/runs/7265009429?check_suite_focus=true#step:23:12)7.

on nx 1.4.2

**Comment by nhhockeyplayer** [comment]
volta is showing up in the logs... nothign is working
this is starting to not be fun
being burned out by poiints of failure
