### ISSUE TITLE
Micro Frontend Host generation uses CSS not --style or NX.json config

### ISSUE THREAD

**Issue by pandabuilt** [nrwl/nx#9760]
Using NX as a monorepo with microfrontends - generating both host and remote
`npx nx g @nrwl/angular:host app-shell`

`npx nx g @nrwl/angular:remote login --host=app-shell`

I tried passing `style=scss` and no dice.  

I also tried generating an app with mfe and host as the type - but then ran into other micro front end modular federation problems.

note that when I created it - it created "css" inside nx.json inside angular:application.  I changed that to scss and even generated / regenerated host / remotes - and it still used css .

`{
  "npmScope": "app",
  "affected": {
    "defaultBase": "master"
  },
  "implicitDependencies": {
    "angular.json": "*",
    "package.json": "*",
    "tslint.json": "*",
    ".eslintrc.json": "*",
    "nx.json": "*",
    "tsconfig.base.json": "*"
  },
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "cli": {
    "defaultCollection": "@nrwl/angular"
  },
  "generators": {
    "@nrwl/react": {
      "application": {
        "style": "scss",
        "linter": "eslint",
        "babel": true
      },
      "component": {
        "style": "scss"
      },
      "library": {
        "style": "scss",
        "linter": "eslint"
      }
    },
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
    "@nrwl/angular:component": {
      "style": "scss"
    }
  },
  "defaultProject": "app"
}`

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by gioragutt** [comment]
Can you post the output of `nx report`?

**Comment by pandabuilt** [comment]
` >  NX   Report complete - copy this into the issue template

   Node : 16.14.1
   OS   : darwin arm64
   npm  : 8.5.0
   
   nx : 13.10.0
   @nrwl/angular : 13.10.0
   @nrwl/cypress : 13.10.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.1.3
   @nrwl/eslint-plugin-nx : 13.10.0
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.0
   @nrwl/js : 13.9.7
   @nrwl/linter : 13.10.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.7
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.0
   @nrwl/web : 13.9.7
   @nrwl/workspace : 13.9.7
   typescript : 4.5.5
   rxjs : 7.5.4
   ---------------------------------------
   Community plugins:
   	 @nxtend/firebase: 12.1.0
   	 @nativescript/nx: 3.0.10
   	 @ngneat/tailwind: 7.0.3

(node:53772) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/a/app/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)`

**Comment by Coly010** [comment]
Fixed by this: https://github.com/nrwl/nx/pull/9751
and released in `13.10.1`.

Thanks for reporting!

I'll close this as it has been addressed already
