### ISSUE TITLE
v13.10.0 - Cypress does not respect env cli params (regression)

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#9764]
## Current Behavior
Seems like a regression of https://github.com/nrwl/nx/issues/8723

```sh
   Node : 16.13.0
   OS   : darwin x64
   yarn : 3.2.0
   
   nx : 13.10.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.1
   @nrwl/eslint-plugin-nx : 13.10.1
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.1
   @nrwl/js : 13.10.1
   @nrwl/linter : 13.10.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.1
   @nrwl/web : 13.10.1
   @nrwl/workspace : 13.10.1
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         nx-stylelint: 13.3.0

```

**Comment by barbados-clemens** [comment]
this looks to be an issue with what the executor is provided via nx. 
as cypress executor is given the env vars just still in dot notation

nx v12
![console log showing env vars are parsed as an object](https://user-images.githubusercontent.com/23272162/163034112-922ff4d2-def1-4447-9b5c-28a42caf8c34.png)

nx v13 
![console log showing env vars are still in dot notation](https://user-images.githubusercontent.com/23272162/163034217-3c4eebe3-61cc-46e2-a2ec-d5b77a3c61ab.png)


[looks to be a regression when we shuffled around the inner guts of nx](https://github.com/nrwl/nx/blob/d4b5c30eba94cb3fa718e35fb60ebe5b3636a7a3/packages/nx/src/command-line/nx-commands.ts#L29) on commit d4b5c30eba94cb3fa718e35fb60ebe5b3636a7a3

[here is the PR to fix it](https://github.com/nrwl/nx/pull/9812)
