### ISSUE TITLE
v13.10.0 - Nestjs hotreload is not working

### ISSUE THREAD

**Issue by PezeM** [nrwl/nx#9766]
## Current Behavior

Newly created nestjs application using the [docs](https://nx.dev/nest/overview) and the command `npx create-nx-workspace my-workspace --preset=nest` has not working hot reload. By default when you create nestjs application there is built in hot reload module which will reload the application on code changes.

## Expected Behavior
Running `npm run start` command in newly created nx workspace with nestjs should behave similar to running `npm run start:dev` in newly created nestjs application - watching the files and reloading the servers when there are any changes.

## Steps to Reproduce

1. Run `npx create-nx-workspace my-workspace --preset=nest`
2. Finish the setup
3. Enter `my-workspace` directory
4. Run `npm run start` command
5. Change the nestjs code in `apps/<application name/src` directory
6. Server is not reloading

### Environment

```
 Node : 16.13.0
 OS   : linux x64
 npm  : 7.5.6

 nx : 13.10.1
 @nrwl/angular : Not Found
 @nrwl/cypress : Not Found
 @nrwl/detox : Not Found
 @nrwl/devkit : 13.10.1
 @nrwl/eslint-plugin-nx : 13.10.1
 @nrwl/express : Not Found
 @nrwl/jest : 13.10.1
 @nrwl/js : 13.10.1
 @nrwl/linter : 13.10.1
 @nrwl/nest : 13.10.1
 @nrwl/next : Not Found
 @nrwl/node : 13.10.1
 @nrwl/nx-cloud : 13.2.2
 @nrwl/nx-plugin : Not Found
 @nrwl/react : Not Found
 @nrwl/react-native : Not Found
 @nrwl/schematics : Not Found
 @nrwl/storybook : Not Found
 @nrwl/web : Not Found
 @nrwl/workspace : 13.10.1
 typescript : 4.6.3
 rxjs : 7.5.5
 ---------------------------------------
 Community plugins:
```

**Comment by romshiri** [comment]
Same with the default Next.js project. Perhaps related. #9782

**Comment by PezeM** [comment]
@AgentEnder Sorry, but how is Nestjs related to Nextjs?

**Comment by AgentEnder** [comment]
Whoops! Good shout, this is not a duplicate, then, as the Next issue was caused on NestJS's side. I misread some things. I blame the JS ecosystem's names for being similar. I'll reopen this now. 😅

**Comment by DeepaPrasanna** [comment]
Hey! May I know if there are any updates to this issue. I have been facing this same issue.

**Comment by muhammaduxair** [comment]
> Hey! May I know if there are any updates to this issue. I have been facing this same issue.

Same here pls update.
