### ISSUE TITLE
Cannot find module '@nrwl/workspace/src/utilities/perf-logging'

### ISSUE THREAD

**Issue by patrick1729** [nrwl/nx#9769]
## Current Behavior

I am trying to add a service worker in my Angular application with the command:
`ng add @angular/pwa --project *project-name*`
keep getting error:
`Cannot find module '@nrwl/workspace/src/utilities/perf-logging'`

My global Nx version is the same as project version 13.10.1. 
I referred similar issues:

- https://github.com/nrwl/nx/issues/4656 and none of the comments helped as all of my @nrwl/* dependencies are of same version.

- I also checked issue https://github.com/nrwl/nx/issues/9354.

## Expected Behavior

The service worker should be created without errors

### Failure Logs

```
Unknown error: Error: Cannot find module '@nrwl/workspace/src/utilities/perf-logging'
Require stack:
- D:\whatsapp-clone\node_modules\@nrwl\cli\lib\init-local.js
- D:\whatsapp-clone\node_modules\@nrwl\cli\bin\nx.js
- D:\whatsapp-clone\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\DELL\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
```

### Environment

```
   Node : 14.16.0
   OS   : win32 x64
   npm  : 6.14.11

   nx : 13.10.1
   @nrwl/angular : 13.10.1
   @nrwl/cypress : 13.10.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.1
   @nrwl/eslint-plugin-nx : 13.10.1
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.1
   @nrwl/js : 13.10.1
   @nrwl/linter : 13.10.1
   @nrwl/nest : 13.10.1
   @nrwl/next : Not Found
   @nrwl/node : 13.10.1
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.1
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.1
   typescript : 4.6.3
   rxjs : 7.5.5
```

**Comment by AgentEnder** [comment]
Looking at the require stack in your error log, it looks like its trying to load Nx through @nrwl/cli which no longer exists. Its possible the decorate angular cli file in your repo has become out of date.

In any case, can you run `npm i @angular/pwa && nx g @angular/pwa:ng-add` instead? It should work.

**Comment by leosvelperez** [comment]
Could you share a repo where this issue can be reproduced?
