### ISSUE TITLE
Jest builder must have NODE_ENV=test

### ISSUE THREAD

**Issue by gvsz** [nrwl/nx#977]
Jest by default sets `NODE_ENV=test`, that behavior is changed when using ng test, making it `undefined`.

**Comment by FrozenPandaz** [comment]
I don't believe we are doing anything to override the default. Can you point to some documentation or a fix?

**Comment by gvsouza** [comment]
Regarding the NODE_ENV, Jest will set process.env.NODE_ENV to 'test' if it's not set to something else.

Taken from https://jestjs.io/docs/en/getting-started.html#using-babel

The only fix I've found os manually set

**Comment by fknop** [comment]
I'm having the same issue!
I had to manually add `process.env.NODE_ENV = 'test'` in the jest global setup.

**Comment by Cammisuli** [comment]
Related source where Jest adds `test` as the `NODE_ENV`:
https://github.com/facebook/jest/blob/446d174fc040247d945e2f682561339a54364323/packages/jest-cli/bin/jest.js#L12-L14

It's in the bin file.
