### ISSUE TITLE
Nx target does not fallback to npm script when runned from a project's root rather than the workspace root

### ISSUE THREAD

**Issue by melMass** [nrwl/nx#9772]
I'm not sure which part of nx is responsible of that, but when you don't specify a target in `project.json` it falls back to running the package.json's script with the same name.

I'm relying on this behavior in a few packages of my monorepo, but I'm facing this issue when running nx in the workspace subfolders.

## Current Behavior
:white_check_mark: `nx build my-package` - from the workspace root works.
:no_entry_sign: `nx build` - from “packages/my-package” returns:
```
Error: Cannot find configuration for task my-package:build
```
https://app.warp.dev/block/0yOq2zL20xxSg0nPoRSLDf

:white_check_mark: `nx build` - from “packages/my-package” with a build target defined in project.json works

---

I removed steps to reproduce as I don't think it's relevant, please tell me if you need more informations.

### Environment
```ruby
Node : 16.7.0
   OS   : darwin x64
   pnpm : 6.32.4

   nx : 13.10.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.1
   @nrwl/eslint-plugin-nx : 13.10.1
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.1
   @nrwl/js : 13.10.1
   @nrwl/linter : 13.10.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.1
   @nrwl/nx-cloud : 13.2.2 --> seems to be the wrong version but I don't use it in this project
   @nrwl/nx-plugin : 13.10.1
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 13.10.1
   @nrwl/workspace : 13.10.1
   typescript : 4.7.0-dev.20220406
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nx-plus/docusaurus: 12.2.0
         @nxext/svelte: 13.3.0
         @nxext/vite: 13.2.4
         @nxrs/cargo: 0.3.2
         @trumbitta/nx-plugin-unused-deps: 1.10.0

```

**Comment by AgentEnder** [comment]
Link to relevant community slack discussion: https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1649603608270299?thread_ts=1649382513.177719&cid=CMFKWPU6Q
