### ISSUE TITLE
ng update adding ngrx packages to devDependencies

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#978]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

The existing references to ngrx in dependencies should be updated

## Current Behavior

new dependencies for ngrx are being added in devDependencies and old references are left in place

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run ng update @nrwl/schematics

This is the offending code:
`updateJsonInTree('package.json', json => {
      json.devDependencies = json.devDependencies || {};
      json.devDependencies = {
        ...json.devDependencies,
        '@ngrx/effects': '6.1.2',
        '@ngrx/router-store': '6.1.2',
        '@ngrx/schematics': '6.1.2',
        '@ngrx/store': '6.1.2',
        '@ngrx/store-devtools': '6.1.2'
      };

      return json;
    }),`

**Comment by FrozenPandaz** [comment]
Sorry about that. Good find! Addressing that asap
