### ISSUE TITLE
@nrwl/workspace fails to properly install if file with no permissions is present

### ISSUE THREAD

**Issue by mp3three** [nrwl/nx#9791]
## Current Behavior

Install fails, provided error logs are not helpful in identifying problem

> yarn install v1.22.17
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> warning " > @emotion/babel-plugin@11.7.2" has unmet peer dependency "@babel/core@^7.0.0".
> warning "@emotion/babel-plugin > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning "@nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor@5.9.1" has unmet peer dependency "@babel/core@^7.0.1".
> warning "@nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor@5.9.1" has unmet peer dependency "@babel/preset-env@^7.0.0".
> warning "@nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor@5.9.1" has unmet peer dependency "babel-loader@^8.0.2".
> warning " > react-test-renderer@18.0.0" has incorrect peer dependency "react@^18.0.0".
> warning "@nrwl/react > @nrwl/web > rollup-plugin-typescript2 > @yarn-tool/resolve-package > @ts-type/package-dts > ts-type@2.1.2" has unmet peer dependency "@types/bluebird@*".
> warning "@nrwl/react > @nrwl/web > rollup-plugin-typescript2 > @yarn-tool/resolve-package > @ts-type/package-dts > ts-type@2.1.2" has unmet peer dependency "ts-toolbelt@^9.6.0".
> warning " > eslint-plugin-jsx-a11y@6.4.1" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
> [4/4] Building fresh packages...
> [-/15] ⠐ waiting...
> [2/15] ⠐ nx
> [3/15] ⠐ cypress
> [-/15] ⠐ waiting...
> error /home/cameron/Repos/nx-examples/node_modules/nx: Command failed.
> Exit code: 1
> Command: node ./bin/init
> Arguments: 
> Directory: /home/cameron/Repos/nx-examples/node_modules/nx
> Output:
> >  NX   Nx Daemon was not able to compute the project graph.
> 
>    Log file with the error: /home/cameron/Repos/nx-examples/node_modules/.cache/nx/d/daemon-error.log
>    Please file an issue at https://github.com/nrwl/nx
>    Nx Daemon is going to be disabled until you run "nx reset".
> 

## Expected Behavior

- Skip over file if no permissions to access it (potentially with warnings)
- Provide file name + hint as to what the error was in the logs somewhere

## Steps to Reproduce

```bash
git clone https://github.com/nrwl/nx-examples
cd nx-examples
touch badfile
chmod 000 badfile
yarn
```

### Failure Logs

> Failed to start the Nx Daemon process.
> Messages from the log:
> 
>  >  NX   Passed 1 file paths to Git to hash, but received 0 hashes.

**Comment by flashart92** [comment]
the problem is relevant
