### ISSUE TITLE
Nx build with configuration and output path is mixing up projects

### ISSUE THREAD

**Issue by jsanta** [nrwl/nx#9809]
We recently started noticing  our apps were down. 
Checked the CI logs and noticed that a build command for a backend app is really running the build command for the frontend app.

## Current Behavior
It becomes clearer with the logs:
```
npm run build-staging backend-app -- --delete-output-path --output-path ./staging/staging-app/server
3m 37s
+ npm run build-staging backend-app -- --delete-output-path --output-path ./staging/staging-app/server
> app@4.0.2 build-staging
> nx build --configuration=staging --optimization=true "backend-app" "--delete-output-path" "--output-path" "./staging/staging-app/server"
> nx run frontend-app:build:staging --optimization=true --deleteOutputPath --outputPath=./staging/staging-app/server
- Generating browser application bundles (phase: setup)...
```
First command `npm run build-staging backend-app -- --delete-output-path --output-path ./staging/staging-app/server` is what runs from the pipeline script.
Looking at the last 2 commands  with the > prefix:
`nx build --configuration=staging --optimization=true "backend-app"`
and then
`nx run frontend-app:build:staging --optimization=true `

Somehow, the backend build is mapped to the frontend build.

## Expected Behavior
Backend build should build the backend-app and not the frontend-app.

## Steps to Reproduce

- `npm install -g nx `
- Create a workspace with a frontend app (angular) and a backend app (express).
- Configure a couple of different environments for both apps.
- Run the build commands, first the frontend, then the backend.

### Environment
› npm run nx report

> app@4.0.2 nx /Users/JSanta/Desarrollos/app
> nx "report"

 >  NX   Report complete - copy this into the issue template

   Node : 14.18.2
   OS   : darwin x64
   npm  : 6.14.15
   
   nx : 13.10.0
   @nrwl/angular : 13.8.5
   @nrwl/cypress : 13.8.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.1.3
   @nrwl/eslint-plugin-nx : 13.8.5
   @nrwl/express : 13.8.5
   @nrwl/jest : 13.8.5
   @nrwl/js : 13.8.5
   @nrwl/linter : 13.8.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.8.3
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.8.0
   @nrwl/web : 13.8.5
   @nrwl/workspace : 13.8.5
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.9.0
         @nebular/theme: 8.0.0
         @ng-bootstrap/ng-bootstrap: 10.0.0
         @nguniversal/express-engine: 13.1.0
         @ngx-formly/schematics: 5.10.33
         @scullyio/init: 1.0.1
         @nguniversal/builders: 13.1.0
         @storybook/angular: 6.4.19
         sequelize-generator-schematic: 1.1.1

This is my local configuration which happens to have the same problem as our Bitbucket pipeline.
A coworker tried the same on his machine and the only difference is the nx version, he has 13.9.7 and it doesn't give the problem.

**Comment by jsanta** [comment]
An additional detail.
Forced the 13.9.7 version on our bitbucket pipeline.
Everything seems to be working correctly on that version.

**Comment by AgentEnder** [comment]
Hey @jsanta!

This is very possibly being caused by the mismatched package versions, as some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by jsanta** [comment]
Hi again.
Did a nx migrate. 
Found another bug. In our packjage.json script section:
`"build-prod": "nx build --configuration production --optimization=true`

We have more than a few frontend apps. If I run the script like:
`npm run build-prod frontend-app2 -- --delete-output-path --output-path ./client`
to build ` frontend-app2` it still runs the script to build the default app configured in the `angular.json` file.

```
› npm run build-prod frontend-app2 -- --delete-output-path --output-path ./client

> app@4.0.2 build-prod
> nx build --configuration production --optimization=true "frontend-app2" "--delete-output-path" "--output-path" "./client"


> nx run frontend-app:build:production --optimization=true --deleteOutputPath --outputPath=./client
```
This is not happening in version 13.9.7

The only way of building with additional parameters is modifying the script to:
`"build-prod": "nx build --configuration production --optimization=true --project",`

Only happens when the script has additional parameters (such as environment configurations).

**Comment by AgentEnder** [comment]
Its possible that this was affected by updating the version of `yargs`, which is used to bootstrap our CLI commands. In this case, I think that would be preferred as adding `--project` makes the intention of your command much clearer. Specifying the project name as a positional argument only works when there are not other arguments before it, as it is a **_positional_** argument when specified without a flag.

**Comment by jsanta** [comment]
Agreed on adding the --project  parameter for clarity.
The thing is that this kind of breaking changes were not expected on a minor version update.
Will close the issue. Thanks for every advice :)
