### ISSUE TITLE
Nx not recomputing cache when index.html changes by scirpts

### ISSUE THREAD

**Issue by tirelyl** [nrwl/nx#9814]
## Current Behavior

same as title，nx not recomputing cache when index.html changes by scirpts
## Expected Behavior

when index.html changes by script, nx will recomputing cache.

## Steps to Reproduce

I have a angular workspace with Nx. I use gulp to build the project. In gulp's task, I created a task that dynamically generates `index.html` before running `nx build`. when I use parameters to change the generation of index.html, nx does not recalculate the cache.

output of the gulp task
![image](https://user-images.githubusercontent.com/20921324/163091536-46314884-6e0a-4c0e-a553-ac6c6423c1f0.png)

`angular.json`
![image](https://user-images.githubusercontent.com/20921324/163091739-4f90a5bc-921a-4dbe-b1eb-592e7996e028.png)

This problem has puzzled me for a long time, and I have looked for a lot of solutions, but I can't find a solution, any help will be greatly appreciated

### Environment

  @nrwl/angular : 12.10.1
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 12.10.1
  @nrwl/devkit : 12.10.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 12.10.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by AgentEnder** [comment]
@tirelyl Is there a public repo that demonstrates this issue? If not, can you put together a small reproduction so that we can investigate?

**Comment by tirelyl** [comment]
I found the reason for the bug when i make the reproduction. When I add `index.html` to `.gitignore` file, every time I modify `index.html` and then compile the code, nx will always only read the cache of the first compilation.

the link of the reproduction is here 👉🏻 [https://github.com/tirelyl/nx-build-demo](url)

You can reproduce this problem by following my steps below

1. Make sure to add `index.html` to the `.gitignore`
<img width="451" alt="image" src="https://user-images.githubusercontent.com/20921324/163301341-ca2e4eec-81c0-473a-9e76-97f65ecea098.png">

2. Complete `index.html` and compile the project once
<img width="806" alt="image" src="https://user-images.githubusercontent.com/20921324/163301618-29309a75-85e4-4e8f-be61-b915054546b4.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/20921324/163301915-6b35ec66-25ea-4fec-bc65-e1e0bef66777.png">

3. Change something in `index.html`, then compile again
<img width="719" alt="image" src="https://user-images.githubusercontent.com/20921324/163302171-78b9d643-8306-47a8-a161-aa2bcba771b0.png">
<img width="843" alt="image" src="https://user-images.githubusercontent.com/20921324/163302247-f053ad26-1d09-4647-b06e-a3180a29a989.png">

The scenario I am facing now is like this, I have many different environments that need to use ejs to dynamically generate different `index.html` templates, so I don't want to submit the frequently changed `index.html` to the git repository. I'm wondering why the `.gitignore` file causes the cache not to be recalculated

**Comment by galah92** [comment]
@tirelyl I have got the exact same problem with code generation from OpenAPI spec - Nx doesn't recompute cache. Did you solve this?

**Comment by tirelyl** [comment]
> @tirelyl I have got the exact same problem with code generation from OpenAPI spec - Nx doesn't recompute cache. Did you solve this?

as i sayed above, the file that added in `.gitignore` will caused nx not recompute the cache. so i resolve this problem by removing the file from the `.gitignore`

**Comment by AgentEnder** [comment]
Its intended behavior that ignored files aren't included in the hash. The fix in most cases is that whatever is generating the ignored file, or determining its contents, needs to be included in the build inputs
