### ISSUE TITLE
next.js NextImage's broken

### ISSUE THREAD

**Issue by bonesoul** [nrwl/nx#9822]
I've been using the trick here to fix optimized next.js image components:

https://storybook.js.org/blog/get-started-with-storybook-and-next-js/

```
// .storybook/preview.js
import * as NextImage from "next/image";

const OriginalNextImage = NextImage.default;

Object.defineProperty(NextImage, "default", {
  configurable: true,
  value: (props) => <OriginalNextImage {...props} unoptimized />,
});
```

though with latest builds, it seems to be broken. any fixes?

**Comment by dkozickis** [comment]
Did you figure it out @bonesoul ?

**Comment by bonesoul** [comment]
well i mis-created this issue in this repo. sorry for that :/

**Comment by dkozickis** [comment]
But do you have any solution? 😅
