### ISSUE TITLE
Docs for the jest integration leads to the generation error

### ISSUE THREAD

**Issue by meskill** [nrwl/nx#9825]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

[jest integration](https://nx.dev/jest/overview#adding-jest-to-an-existing-project)

### Additional context or description

I'm trying to integrate `nx` to the existing yarn project.

After following base guide for [migration](https://nx.dev/migration/adding-to-monorepo) I managed to run basic commands like `build` through `nx`.

Then I've tried to integrate jest nx integration following [this doc](https://nx.dev/jest/overview#adding-jest-to-an-existing-project) but after running command `nx g @nrwl/jest:jest-project --project=<project-name>` as docs suggests in order to add jest integration to the existing project I've got next error.

```
Cannot read properties of undefined (reading 'test')
```

with `--verbose`:
```
Cannot read properties of undefined (reading 'test')
TypeError: Cannot read properties of undefined (reading 'test')
    at checkForTestTarget (/workspaces/Tinkoff/tramvai/node_modules/@nrwl/jest/src/generators/jest-project/lib/check-for-test-target.js:8:29)
    at /workspaces/Tinkoff/tramvai/node_modules/@nrwl/jest/src/generators/jest-project/jest-project.js:46:56
    at Generator.next (<anonymous>)
    at /workspaces/Tinkoff/tramvai/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/workspaces/Tinkoff/tramvai/node_modules/tslib/tslib.js:113:16)
    at jestProjectGenerator (/workspaces/Tinkoff/tramvai/node_modules/@nrwl/jest/src/generators/jest-project/jest-project.js:43:20)
    at Object.<anonymous> (/workspaces/Tinkoff/tramvai/node_modules/nx/src/command-line/generate.js:128:36)
    at Generator.next (<anonymous>)
    at fulfilled (/workspaces/Tinkoff/tramvai/node_modules/tslib/tslib.js:114:62)
```

There is probably some missing steps for the jest integration as docs covers this very briefly.

**Comment by barbados-clemens** [comment]
can you share the project configuration for the project you're trying to add jest to?

**Comment by meskill** [comment]
@barbados-clemens The problem happens if there is no `project.json` config inside package.

My project is monorepo based on yarn workspaces. I've tried to follow [migration guide](https://nx.dev/migration/adding-to-monorepo) and just using npm scripts worked fine for me. Then I tried to add jest and got the error above. I don't see any details that having project config is required to add jest.

I think error message should be more descriptive and provide suggestion how to fix it.

**Comment by barbados-clemens** [comment]
npm scripts are new-ish so there is just some growing pains with it. I assume it's because when we read the project configuration for this project that it comes back without targets. so the generator is [hitting a null ref when checking for an existing test target](https://github.com/nrwl/nx/blob/a2b704df54a9b6b554972bff3010212041bada83/packages/jest/src/generators/jest-project/lib/check-for-test-target.ts#L6). 

making a project.json with an empty targets object should fix the issue
```json
"targets": {}
```

if you don't want to use project.json can you try adding
```json
"nx": {
  "targets": {}
}
```
in your package.json and see if the problem still happens?
