### ISSUE TITLE
Add json schema to nx configuration files

### ISSUE THREAD

**Issue by meskill** [nrwl/nx#9826]
## Description

Consider adding json schema to the [JSON Schema Store](https://www.schemastore.org/json/) or through other external link.

## Motivation

Using json schema will help users with nx configuration as it is provides linting and intellisense in the advanced code editors, e.g. [Visual Studio Code](https://code.visualstudio.com/Docs/languages/json#_json-schemas-and-settings)

**Comment by AgentEnder** [comment]
I'm going to close this out for now, as json schema support has been discussed in the past for configuration files. The short story is that its not super feasible for `workspace.json`, but we provide these schemas via nx console as it is able to generate the schema dynamically.

See discussion on adding json schema support for Nx / workspace.json here: https://github.com/nrwl/nx/issues/9475
