### ISSUE TITLE
Schematics: add environments similar to generated for app to library project

### ISSUE THREAD

**Issue by muradm** [nrwl/nx#983]
Currently, new app has `src/environments/environment.ts` and `src/environments/environment.prod.ts` with necessary `angular.json` configuration by default. Generated library projects does not have that.

While possible to do:
```
// TODO: have another set of environments for library
// tslint:disable-next-line
import { environment } from '../../../../apps/frontend/src/environments/environment';
```
Which is not very modular and adds `ts-lint` errors.

Better way would be to have `src/environments` exist for library projects and inherit type of build (dev/prod/etc.) from application build options.

**Comment by xmlking** [comment]
this feature is good for generating publishable  micro-apps (a.k.a angular element) in `libs` folder.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
