### ISSUE TITLE
The path provided for the SCAM does not exist under the project root

### ISSUE THREAD

**Issue by guysenpai** [nrwl/nx#9835]
## Current Behavior

When I want to generate SCAM from `@nrwl/angular` with path via NX Console I get the error `The path provided for the SCAM (...) does not exist under the project root (...)`.

## Expected Behavior

Generate the SCAM on the specified path folder.

## Steps to Reproduce

- Go to NX Console
- choose generate `@nrwl/angular - scam`
- enter a name
- select a project
- enter an existing path from the project root

### Failure Logs

```
> Executing task: pnpm exec nx generate @nrwl/angular:scam --name=card --project=fuse --style=scss --changeDetection=OnPush --flat --no-inlineScam --path=components/card/src --prefix=fuse --skipTests --viewEncapsulation=None --no-interactive --dry-run <

The path provided for the SCAM (components/card/src) does not exist under the project root (libs/fuse).
The terminal process "/bin/zsh '-c', 'pnpm exec nx generate @nrwl/angular:scam --name=card --project=fuse --style=scss --changeDetection=OnPush --flat --no-inlineScam --path=components/card/src --prefix=fuse --skipTests --viewEncapsulation=None --no-interactive --dry-run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

### Environment

Node : 16.13.0
   OS   : darwin x64
   pnpm : 6.32.6
   
   nx : 13.10.1
   @nrwl/angular : 13.10.1
   @nrwl/cypress : 13.10.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.1
   @nrwl/eslint-plugin-nx : 13.10.1
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.1
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.1
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.1
   typescript : 4.6.3
   rxjs : 7.4.0

**Comment by Coly010** [comment]
Can you share folder structure?

You do not need to give a path. In this case, your `path` would be something like: `libs/fuse/src/lib/components/card/src`.

**Comment by guysenpai** [comment]
this is my folder structure

<img width="287" alt="Capture d’écran 2022-04-15 à 19 41 07" src="https://user-images.githubusercontent.com/6205146/163603250-ce1bbc18-f1ca-4c64-83ae-1ddd82ae556c.png">
