### ISSUE TITLE
add support for notDependOnLibsWithTags like onlyDependOnLibsWithTags

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#984]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

 
## Expected Behavior

Today we cannot define all `nx-enforce-module-boundaries`  with `onlyDependOnLibsWithTags` . Would be nice to have `notDependOnLibsWithTags` DSL  to express forbid cases.

e.g., 
`lazy loaded modules` should not have dependency on   `eager loaded modules` but can depend on `shared modules` 

## Current Behavior

What is the current behavior?
we only have `onlyDependOnLibsWithTags` and it is limited to express more specific rules. 

 
 ## Version
nx v.3.0

**Comment by maxime1992** [comment]
I find the `onlyDependOnLibsWithTags` quite restrictive too and I'm having a hard time trying to set some rules. `notDependOnLibsWithTags` would really be helpful :)

**Comment by kkuriata** [comment]
Yes, please add this prop!

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by maxime1992** [comment]
Keep active.

**Comment by zbarbuto** [comment]
Not stale. Still a feature I would like.

**Comment by jaytavares** [comment]
This feature is needed. It's pretty limiting/cumbersome if we only have `onlyDependOnLibsWithTags` at our disposal. We really need the inverse as well. It's actually pretty odd that we don't already have `notDependOnLibsWithTags` considering that in Nrwl's official "Enterprise Angular Monorepo Patterns" book, all the constraints are described in terms of what apps/libs _cannot_ depend on:

>## Built-in Constraints on Libraries
>The following invariants should hold true: 
> 1. a lib cannot depend on an app
> 2. an app-specific library cannot depend on a lib from another app (e.g., "safe/" can only depend on libs from "safe/" or shared libs)
> 3. a shared library cannot depend on on a app-specific lib (e.g., "common-ui/" cannot depend on "safe/")
> 4. a ui library cannot depend on a feature library, or a data-access library.
> 5. a utils library cannot depend on a feature library, data-access library, or a component library.
> 6. a data-access library cannot depend on a feature library, or a component library.
> 7. a project cannot have circular dependencies
> 8. a project that lazy loads another project cannot import it directly.

**Comment by jaytavares** [comment]
Not stale. I actually wrote an implementation of this rule on my fork; however, I discovered that we'll probably want to traverse the project graph to ensure no dependencies of dependencies have the disallowed tags. I'll try to find some time to finish that soon.

**Comment by jaytavares** [comment]
See #8633 for my implementation of this. Feedback appreciated
