### ISSUE TITLE
Modifying app tsconfig.json causes all apps to show in affected:apps

### ISSUE THREAD

**Issue by ComradeCow** [nrwl/nx#985]
## Expected Behavior

When modifying the `tsconfig.json` for one application, other applications should not be marked as modified by `yarn run affected:apps`

## Current Behavior

Every other app in the workspace is marked as affected.

## Failure Information (for bugs)

Using the following steps, I expected the output of `yarn run affected:apps --base=master --head=HEAD` to be `app2`.  Instead, the output is `app2 app1`.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone my [sample repository](https://github.com/ComradeCow/affected-apps-workspace-bug)
2. `yarn`
3. `git checkout touch-tsconfig`
4. `yarn run affected:apps --base=master --head=HEAD`

### Context

I set up the workspace using `create-nx-workspace affects-apps-workspace`, then created the apps with `ng g @nrwl/schematics:application app[X] --prefix=app[X] --e2eTestRunner=none`.  My global `@nrwl/schematics` was 7.3.0.

We have a workspace with 38 projects (apps, libs, e2e) at work. We rely on the `affected:*` scripts for a pre-push hook and for our CI tests.  

I modified the new (as of 7.2?) `tsconfig.json` for one of our applications to add a new compile option. I was surprised when our pre-commit hook reported I modified everything.  I assumed modifying the tsconfig would only affect that one app.

**Comment by fvanwijk** [comment]
Do you have `"tsconfig.json": "*"` in your nx.json file?
It is meant for the tsconfig.json on root level but might also match the tsconfig.json files in your apps.

**Comment by FrozenPandaz** [comment]
Yeah, this is a bug in this line: https://github.com/nrwl/nx/blob/230483d0c02735caa88cef101517ca96adec9ea5/packages/schematics/src/command-line/touched.ts#L43

The context for the `endsWith` is https://github.com/nrwl/nx/pull/850

WIll try to address soon

**Comment by Merott** [comment]
Any updates on this? Running into the same issue :)
