### ISSUE TITLE
Nx cache always returns results from cache even when source files have changed

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#9852]
## Current Behavior

In my current Nx repo, any project that I build with `nx build` is being cached regardless of whether source files change. If no cache entry exists it will rebuild, but after that it will always return from the cache no matter what. 
## Expected Behavior

The cache should be invalidated by source files changing
## Steps to Reproduce

The repo where I'm experiencing the issue is open source:
https://github.com/DevCycleHQ/js-sdks

The cache was working fine up until recently. I believe I've narrowed down where the problem was introduced to this PR:
https://github.com/DevCycleHQ/js-sdks/pull/103

But I'm not sure what changes are causing it

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   yarn : 3.2.0

   nx : 13.9.3
   @nrwl/angular : undefined
   @nrwl/cypress : 13.9.3
   @nrwl/detox : 13.10.1
   @nrwl/devkit : 13.9.3
   @nrwl/eslint-plugin-nx : 13.9.3
   @nrwl/express : undefined
   @nrwl/jest : 13.9.3
   @nrwl/js : 13.9.3
   @nrwl/linter : 13.9.3
   @nrwl/nest : undefined
   @nrwl/next : 13.9.3
   @nrwl/node : 13.9.3
   @nrwl/nx-cloud : undefined
   @nrwl/nx-plugin : undefined
   @nrwl/react : 13.9.3
   @nrwl/react-native : 13.9.3
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.9.3
   @nrwl/web : 13.9.3
   @nrwl/workspace : 13.9.3
   typescript : 4.3.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Hey @ajwootto! files included in `.gitignore` are not hashed. It appears the PR introduced `/` in the .gitignore on line 90, thus ignoring the whole repo. 

Removing that line should fix this. Feel free to comment if it needs to be reopened.

**Comment by ajwootto** [comment]
confirmed that was the issue, sorry for the trouble!
