### ISSUE TITLE
`tsc --noEmit` loses colors because `process.stdout.isTTY` is not true when running with nx

### ISSUE THREAD

**Issue by elado** [nrwl/nx#9856]
## Current Behavior

Running a type check using `tsc --noEmit` with nx loses the colors which default to true when `process.stdout.isTTY` is true

![image](https://user-images.githubusercontent.com/51488/163616375-a865c35a-06e5-4282-90e4-6f6408b7d995.png)

Running outside of nx:
![image](https://user-images.githubusercontent.com/51488/163615808-f494e654-5646-4f08-9f37-58f3f953b339.png)

TS checks for `process.stdout.isTTY`:
https://github.com/microsoft/TypeScript/blob/3fd8a6e44341f14681aa9d303dc380020ccb2147/src/executeCommandLine/executeCommandLine.ts#L71
https://github.com/microsoft/TypeScript/blob/8d9fa685b5a759f2dab9898e7a75de1cb675c188/src/compiler/sys.ts#L1321

## Expected Behavior
Given that Nx [says here](https://nx.dev/guides/turbo-and-nx#:~:text=Nx%20doesn%27t%20change%20your%20terminal%20output.%20Spinners%2C%20animations%2C%20colors%20are%20the%20same%20whether%20you%20use%20Nx%20or%20not
)
> Nx doesn't change your terminal output. Spinners, animations, colors are the same whether you use Nx or not

I'd expect that tsc colors would be there. I'm not sure about the semantics of TTY.

## Steps to Reproduce
Any source with failing `tsc --noEmit`, like `const a: number = "s"`

### Environment

```
   Node : 16.13.1
   OS   : darwin arm64
   yarn : 3.1.1
   
   nx : 13.10.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.1
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.1
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.1
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by elado** [comment]
Not stale

**Comment by Ni55aN** [comment]
same problem
