### ISSUE TITLE
Angular MFE Module build failed missing from the typescript compilation

### ISSUE THREAD

**Issue by ak274** [nrwl/nx#9861]
## Current Behavior

1) Create workspace using latest version 13.10.2 
2)  Create one host app with Dynamic MFE true, one remote app using mfe-setup schematics 
3)  Create  one shared library which is being import by remote application or both. 
Now when you will run `nx serve-mfe` , build will fail with error attached in screenshot below.
![image](https://user-images.githubusercontent.com/16129430/163787824-0c1d2ac0-7819-4d0e-af29-f5f02b5a81e7.png)
## Expected Behavior

It shouldn't fail and should serve the host application.

## Steps to Reproduce

Here is a repo i have created to reproduce the issue

https://github.com/ak274/test-org

**Comment by Coly010** [comment]
Unable to reproduce on macOS and Linux. Will try again on Windows.
