### ISSUE TITLE
How to ignore specific files/folders from eslint

### ISSUE THREAD

**Issue by gbeford** [nrwl/nx#9868]
### Discussed in https://github.com/nrwl/nx/discussions/9857

<div type='discussions-op-text'>

<sup>Originally posted by **gbeford** April 15, 2022</sup>
I have a huge project that we want to convert from tslint to eslint. Because its so big we want to do this in small chunks which is why we want to be able to ignore folders. Does anyone know how to do this?

I have tried to add 
 ``  "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "apps/something/src/**/*.ts",
              "apps/something/src/**/*.html"
            ]
          },
          "excludes":[
            "apps/something/src/app/client-side/utils/*.ts"
          ]
        },
``
However this seems to not exclude the file at all? 

But if I do the reverse like this it does only lint this one file

``   "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
           "apps/something/src/app/client-side/utils/*.ts"
            ]
          }
          ]
        },
``
Can someone tell me if there is a bug with excludes? or if I am not doing this correctly?

any help is greatly appreciated :)</div>

**Comment by adam-marshall** [comment]
what was the solution @gbeford ?

I'm trying to use `--no-error-on-unmatched-pattern` option, as I am using the .eslintignore file to ignore directories, but this will still fail if no files were found.
