### ISSUE TITLE
Generating component fails in fresh angular workspace

### ISSUE THREAD

**Issue by sh33dafi** [nrwl/nx#9869]
## Current Behavior
running nx g c <component-name> results in an error

## Expected Behavior
a component with the given name should be generated, this used to work

## Steps to Reproduce
I have this issue in this repo https://github.com/sh33dafi/dart-score

What I did was creating a new angular workspace and installed d3
`npx create-nx-workspace@latest`
`npm install d3 && npm install @types/d3 --save-dev`
created a library with `npx nx g c dart-board `

running `nx g c dart-board --project=dart-board` fails with the error

`Cannot read properties of undefined (reading 'exists')`

### Failure Logs
TypeError: Cannot read properties of undefined (reading 'exists')
    at Object.isDirectory (/Users/yannickhoubrix/dev/github/darts-score/node_modules/@schematics/angular/utility/workspace.js:28:26)
    at Object.readWorkspace (/Users/yannickhoubrix/dev/github/darts-score/node_modules/@angular-devkit/core/src/workspace/core.js:58:20)
    at getWorkspace (/Users/yannickhoubrix/dev/github/darts-score/node_modules/@schematics/angular/utility/workspace.js:53:51)
    at /Users/yannickhoubrix/dev/github/darts-score/node_modules/@schematics/angular/component/index.js:101:62
    at Object.<anonymous> (/Users/yannickhoubrix/dev/github/darts-score/node_modules/nx/src/command-line/generate.js:134:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/yannickhoubrix/dev/github/darts-score/node_modules/tslib/tslib.js:114:62)

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin x64
   npm  : 8.5.0
   
   nx : 13.10.2
   @nrwl/angular : 13.10.2
   @nrwl/cypress : 13.10.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.2
   @nrwl/eslint-plugin-nx : 13.10.2
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.2
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 13.3.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.2
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.2
   typescript : 4.6.3
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:

**Comment by oidacra** [comment]
I have a similar error, but my message is `Cannot read property 'exists' of undefined`. the problem shows up when I try to generate a component or lib.
My Nx report

>  NX   Report complete - copy this into the issue template

   Node : 14.19.1
   OS   : darwin x64
   yarn : 1.22.18

   nx : 13.10.0
   @nrwl/angular : 13.10.0
   @nrwl/cypress : 13.10.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.0
   @nrwl/eslint-plugin-nx : 13.10.0
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.0
   @nrwl/js : 13.10.0
   @nrwl/linter : 13.10.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.0
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.0
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.0
   typescript : 4.6.3
   rxjs : 7.5.2
   ---------------------------------------
   Community plugins:
   	 @ngrx/component-store: 13.0.2
   	 @ngrx/effects: 13.0.2
   	 @ngrx/entity: 13.0.2
   	 @ngrx/router-store: 13.0.2
   	 @ngrx/store: 13.0.2
   	 ng-zorro-antd: 13.0.1
   	 @ngrx/schematics: 13.0.2
   	 @ngrx/store-devtools: 13.0.2

**Comment by PieterjanDeClippel** [comment]
ng g c blabla

Fails.

    ng g component blabla

seems to be working fine for me.

**Comment by sh33dafi** [comment]
Same behavior here `nx g component dart-board --project=dart-board` is working
