### ISSUE TITLE
feat(schematics): add additional e2e app with different e2e-test-runner

### ISSUE THREAD

**Issue by skydever** [nrwl/nx#987]
## Expected Behavior

I am running my e2e tests using protractor, but started to migrate to cypress after playing around with it, I really like it. It would be great to be able to create an additional e2e project for an existing app with a different `e2e-test-runner` via schematics, something like:

`ng g e2e-app my-app-cy-e2e --project=my-app --e2e-test-runner=cypress`

that would:

* add entries to `angular.json` + `nx.json`
* create the directory + files for the new e2e project
* check `package.json` for required deps
* missed something (?)

## Current Behavior

I have to create the additional e2e apps by hand, or create my own schematic for this.

## Other

Maybe I can contribute if you tell me what you think about it and how you would do it? I think it could be quite useful for others too (?) (eg. while migrating from protractor to cypress, *double checking* using both test runners ;-), for edge cases that only work with one type of runner ...)

**Comment by skydever** [comment]
I am wondering if creating one e2e-cy app for the complete workspace could be an option (?) - separating the tests per app via folder (or in the app's e2e folder, like for a single project) or something like that, and passing a filter to the cypress runner, what tests to run. the gui can group the tests per app somehow on top level if no filter was passed ... but I guess just for small/mid? sized monorepos suitable? I modified my jest setup to do this (+ be able to run default ng/nx commands), a single jest run for the complete workspace (and I can pass filter), and this seems similair to me ... a layer in between to start the right server (if set so) prior execution - the builder?

**Comment by jordandlaman** [comment]
This is kind of supported now as of nx8.  running ```ng generate @nrwl/cypress:cypress-project``` will scaffold out a new e2e folder with cypress in it.  Can even direct the folder to be nested inside the application.  Does that work?

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by skydever** [comment]
👍
