### ISSUE TITLE
@nrwl/nx-plugin fails when life isn't perfect

### ISSUE THREAD

**Issue by airtonix** [nrwl/nx#9877]
So i'm trying to create a executor in my monorepo... and this happens: 
![image](https://user-images.githubusercontent.com/61225/163958603-c66e30e6-c46c-4033-9f10-cd0fffa32c9e.png)

```
x just nx report                                     
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 17.9.0
   OS   : linux x64
   pnpm : 6.32.8
   
   nx : 13.10.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.2
   @nrwl/eslint-plugin-nx : 13.10.2
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.2
   @nrwl/js : 13.10.2
   @nrwl/linter : 13.10.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 13.10.2
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.2
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.2
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

![image](https://user-images.githubusercontent.com/61225/163956245-f59f4fbf-0cee-40f6-bb7e-826647014282.png)

We should really be validating that all expected things exist before assuming that they do: 

```
function sortObjectByKeys(obj) {
    return Object.keys(obj)
```

which is called by : 
```
            json.devDependencies = sortObjectByKeys(json.devDependencies);
```

---

shouldn't this be : 

```
function sortObjectByKeys(obj) {
    if (!obj || Array.isArray(obj)) return
    return Object.keys(obj)
        .sort()
        .reduce((result, key) => {
        return Object.assign(Object.assign({}, result), { [key]: obj[key] });
    }, {});
}
```

how did this get through code review???!?!

**Comment by airtonix** [comment]
here you could just do : 

```
            json.dependencies = json.dependencies && sortObjectByKeys(json.dependencies) || {};
            json.devDependencies = json.devDependencies && sortObjectByKeys(json.devDependencies) || {};
```

**Comment by airtonix** [comment]
for the record, after that fix: 

![image](https://user-images.githubusercontent.com/61225/163958782-d2de04b2-3c7f-4017-a530-0f91f6a38899.png)

**Comment by airtonix** [comment]
and as an aside: 

we isn't it standard policy in something as configuration heavy as NX that all tooling that uses it have the benfit of all things be validated that they exist before accessing them?

**Comment by gioragutt** [comment]
So what exactly is missing in your project? That you don't have `devDependencies` and it's trying to call `Object.keys(undefined)`?
