### ISSUE TITLE
Plugins link in docs header is broken

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#9879]
### Documentation issue

- [ ] Reporting a typo
- [X] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Additional context or description

The `Plugins` link in the header of the page is broken. It should lead to https://nx.dev/extending-nx/nx-devkit but instead leads to https://nx.dev/getting-started/intro, which means that the link is broken.

The href leads to https://nx.dev/using-nx/nx-devkit, which should be redirected to https://nx.dev/extending-nx/nx-devkit based on the code, but it isn't.

**Comment by AgentEnder** [comment]
This was fixed in #9886
