### ISSUE TITLE
prettier causes tslint errors

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#989]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

formatting should not cause tslint errors

## Current Behavior

typescript code is being formatted so that the line exceeds the max length set in tslint

## Failure Information (for bugs)

I apologize as I am not sure this is a bug for nx but was not sure what to do.  In the latest release there was a new version of prettier added.  since then if I have a long line of code that I put on multiple lines to pass tslint the format job puts it back to one line thus causing tslint error.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. have a long line of code on multiple lines
2. run the format job

### Context

Please provide any relevant information about your setup:
I guess my question is what is the recommended approach to solve this?  Should we disable the max length rule in tslint?

**Comment by jasedwards** [comment]
I was digging through the nx source and I see that a while back you removed the max-line-length rule from tslint on new workspaces.  So I guess my question is would you recommend some way for me to make sure that stays up to date in existing workspaces?  I can of course occasionally check the source and just copy it over but was not sure if this was supposed to be a part of ng update.

**Comment by FrozenPandaz** [comment]
There's more information in this quite old issue: https://github.com/nrwl/nx/issues/224

We try to keep our lint rules consistent with what `prettier` produces and to migrate the `tslint.json` accordingly. I think in general, `prettier` takes priority for lint rules concerning _code formatting_.

This seems to have been a while ago, if you can point to the commit, maybe we can find an older migration to put it in but I don't think it's high priority. In the future though, we'll try our best to migrate `tslint.json` accordingly.

**Comment by jasedwards** [comment]
@FrozenPandaz  Here is the commit.  I think maybe it was just coincidence that we noticed it right after this upgrade of prettier since this was pretty old (1/3/2018)
[https://github.com/nrwl/nx/commit/52cd99c4fa0d7ccb77af2cf1c03e41bc9f111fae](https://github.com/nrwl/nx/commit/52cd99c4fa0d7ccb77af2cf1c03e41bc9f111fael)

**Comment by vsavkin** [comment]
Since we use prettier to format the code, we should not use tslint to do any formatting-related checks. We removed the rules from the generated tslint file some time ago, but we didn't update existing projects.  

I suggest you just remove the formatting-related rules from your tslint json file. Sorry for the inconvenience.
