### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'AuthFacade')

### ISSUE THREAD

**Issue by ryarabala** [nrwl/nx#9894]
Hi Team,
I am currently using angular 11 and nx 11 and upgraded these to version 12 and then 13.

After migration getting the below error while injecting the facade .

@Injectable()
export class SecurityBlueCherryAuthService {
  constructor(
    private apiService: BlueCherryApiService,
    private ngxLoaderService: NgxUiLoaderService
  ) {}

getting exception at second line in the above code.

Console log info below.

security-bc-auth.service.ts:8 Uncaught TypeError: Cannot read properties of undefined (reading 'AuthFacade')
    at Module.AuthFacade (security-bc-auth.service.ts:8:43)
    at Module.65225 (security-domain.module.ts:9:24)
    at __webpack_require__ (bootstrap:19:1)
    at Module.91765 (material.module.ts:107:19)
    at __webpack_require__ (bootstrap:19:1)
    at Module.10092 (auth.actions.ts:35:3)
    at __webpack_require__ (bootstrap:19:1)
    at Module.30396 (security-bc-auth.service.ts:8:43)
    at __webpack_require__ (bootstrap:19:1)
    at Module.9863 (app-routing.module.ts:39:25)

Below security-domain.module.ts

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthFacade } from '@bc/security';
import { SecurityBlueCherryAuthService } from './services/security-bc-auth.service';

@NgModule({
  imports: [CommonModule],
  //providers: [{provide:AuthFacade,useValue: undefined},
  providers: [
    { provide: AuthFacade, useValue: undefined },
    { provide: SecurityBlueCherryAuthService, useValue: undefined },
  ],
})
export class SecurityDomainModule {}

Below auth.facade.ts

@Injectable()
export class AuthFacade {
  user$ = this.store.select(authQuery.getUser);
  isLoggedIn$ = this.store.select(authQuery.getLoggedIn);
  isError$ = this.store.select(authQuery.getError);
  accessToken$ = this.store.select(authQuery.getToken);
  auth$ = this.store.select(authQuery.getAuthData);
  constructor(private store: Store<AuthState>) {}

Please help me out.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you please provide a minimal repo where the issue can be reproduced to help us troubleshoot it?

**Comment by joepvl** [comment]
For posterity: this is a Webpack error that's an indication that you have a circular dependency. Particularly, I've seen this when a file was importing from a sibling module via an index file both modules are exported from, so something like `import { adjacentThing } from '../';` (where `../` refers to `../index.ts`), while in the index file itself this module was listed as an export _before_ the sibling. In the OP's case I would expect such an import to be present in `security-bc-auth.service.ts`. 

Unfortunately, editors' "auto import" functionality tends to write the imports like this sometimes. In such cases you'll need to correct it to import directly from the file the module is defined in instead (like `import { adjacentThing } from '../adjacent-thing/adjacent-thing'`), or from some other place that isn't a common ancestor to both modules.

**Comment by ryarabala** [comment]
Thanks @joepvl 
Its resolved my issue.
