### ISSUE TITLE
Unable to run tests for a specific app

### ISSUE THREAD

**Issue by jon301** [nrwl/nx#99]
It looks like there is no way to run tests for a specific app in a project with multiple apps
The command `ng test --app={appName}` does not work as expected as it runs the tests of all apps.

**Comment by vsavkin** [comment]
It's very difficult to make it work with CLI 1.x. We are working on making Nx work on CLI6, where this should be the default behavior.

**Comment by vsavkin** [comment]
Nx 6 supports running tests for a particular lib. Run`ng test my-lib` or `ng test --project=my-lib`.
