### ISSUE TITLE
reac-cosmos

### ISSUE THREAD

**Issue by vlastoun** [nrwl/nx#9920]
## Description
I would like to use nx workspaces with react-cosmos - similar to storybook

## Motivation
It is faster and better for component development than storybook

## Suggested Implementation
I do not have any clue

## Alternate Implementations
When I put react cosmos configuration 

this is my `cosmos.config.json`

```
{
  "port": 4040,
  "webpack": {
    "configPath": "@nrwl/react/plugins/webpack"
  }
}
```

I am getting TypeError: Cannot read properties of undefined (reading 'rules')

**Comment by AgentEnder** [comment]
This is a good case for a community plugin, if anyone is interested in developing it.
