### ISSUE TITLE
cra-to-nx converts the project successfully however serving the project throws runtime error

### ISSUE THREAD

**Issue by borgdrone7** [nrwl/nx#9926]
## Current Behavior
When I convert my create react app to nx app with cra-to-nx and try to serve it I get runtime error.

## Expected Behavior
When I convert my create react app to nx app with cra-to-nx and try to serve it, it should work.

## Steps to Reproduce
I run "npx cra-to-nx" command in my create react app project folder.
As this converts my whole project it is not possible for me to find an example of this or to provide minimal example as the cra-to-nx works with minimal example. I can add that my create react app was not initially generated with --typescript flag.

### Failure Logs
(node:108358) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
    at my-cra-app/apps/my-nx-app/craco.config.js:27:33
    at Array.find (<anonymous>)
    at my-cra-app/apps/my-nx-app/craco.config.js:26:41
    at Array.forEach (<anonymous>)
    at configure (my-cra-app/apps/my-nx-app/craco.config.js:24:29)
    at giveTotalControl (my-cra-app/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:57:25)
    at mergeWebpackConfig (my-cra-app/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:106:38)
    at overrideWebpackDev (my-cra-app/node_modules/@craco/craco/lib/features/webpack/override.js:11:36)
    at my-cra-app/node_modules/@craco/craco/scripts/start.js:27:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:108358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:108358) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.29s.

### Environment
   Node : 14.19.0
   OS   : linux x64
   yarn : 1.17.3
   
   nx : 13.10.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.3
   @nrwl/eslint-plugin-nx : 13.10.3
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.3
   @nrwl/js : 13.10.3
   @nrwl/linter : 13.10.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.3
   @nrwl/web : 13.10.3
   @nrwl/workspace : 13.10.3
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by devi-prsd** [comment]
+1

**Comment by mandarini** [comment]
This should be fixed in the latest version of Nx. You can follow [this guide](https://nx.dev/recipes/adopting-nx/migration-cra). If issue persists, please ping me and I will reopen this issue!
