### ISSUE TITLE
[fetture request] @nrwl/builders:node-execute WS notification on successfull app start

### ISSUE THREAD

**Issue by Toxicable** [nrwl/nx#994]
## Expected Behavior
The builder should host a WS Server that emits notifications for when a build succesfully passes, so that downstream scripts can "live reload".

## Current Behavior
There is no way to do "live reload" server when using this to do dev with a Universal server without modifying the application code.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
