### ISSUE TITLE
React module federation issue with - in project name

### ISSUE THREAD

**Issue by Elvis116** [nrwl/nx#9941]
## Current Behavior
With @nrwl/react:remote created module federation project, when the project name has - between, it would promote error. But Nx default to add - between project names with several words.

## Expected Behavior
mfe.config.js should allow the name to be customized.

**Comment by jaysoo** [comment]
Hi @Elvis116 can you try this with Nx 14? The one released with 13.10 was an early version that had some bugs.

The naming issue does not exist with Nx 14.
