### ISSUE TITLE
Angular Strorybook generator not adding "projectBuildConfig" to project.json

### ISSUE THREAD

**Issue by KL2808** [nrwl/nx#9944]
## Current Behavior
When executing the __@nrwl/angular:storybook-configuration__ generator, the build config is missing the option: __projectBuildConfig__. In our case, the “angular.json” is pointing to the different projects, and they have their own “project.json” files.

### What we got
```json
    "storybook": {
      "executor": "@nrwl/storybook:storybook",
      "options": {
        "uiFramework": "@storybook/angular",
        "port": 4400,
        "config": {
          "configFolder": "libs/shared/ui-appearance/.storybook"
        },
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
```

## Expected Behavior
The generator should add the “projectBuildConfig”-property to the storybook build config options.

### What should've got
```json
    "storybook": {
      "executor": "@nrwl/storybook:storybook",
      "options": {
        "projectBuildConfig": "shared-ui-appearance",
        "uiFramework": "@storybook/angular",
        "port": 4400,
        "config": {
          "configFolder": "libs/shared/ui-appearance/.storybook"
        },
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
```

## Steps to Reproduce
1. Create a new angular workspace
2. Create a shared-lib
3. move the config from ```angular.json``` to ```{shared-lib}\project.json```.
The ```angular.json``` File should look like this: 
```json
"{shared-lib}": "libs/{shared-lib}",
```
And the ```{shared-lib}\project.json``` File should contain all the config from the ```angular.json``` File.
4. ```npm install @nrwl/storybook --save-dev```
5. ```nx g @nrwl/angular:storybook-configuration --name={shared-lib}```
6. ```nx storybook shared-ui-appearance``` (🧨 Error below)

## Failure Logs
```
nx storybook shared-ui-appearance

> nx run shared-ui-appearance:storybook 

        No projectBuildConfig was provided.
        
        To fix this, you can try one of the following options:
        
        1. You can run the storybook executor by providing the projectBuildConfig flag as follows:

        nx storybook shared-ui-appearance --projectBuildConfig=shared-ui-appearance:build-storybook

        7. In your project configuration, under the "storybook" target options, you can
        set the "projectBuildConfig" property to the name of the project of which you want to use
        the build configuration for Storybook.
```

## Environment

  Node : 14.18.3
  OS   : win32 x64
  npm  : 6.14.15

  nx : 13.6.1
  @nrwl/angular : 13.4.5
  @nrwl/cli : 13.4.5
  @nrwl/cypress : 13.4.5
  @nrwl/devkit : 13.4.5
  @nrwl/eslint-plugin-nx : 13.4.5
  @nrwl/express : undefined
  @nrwl/jest : 13.4.5
  @nrwl/linter : 13.4.5
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.8.7
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.5
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.5
  @nrwl/storybook : 13.10.3
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular-architects/ddd: 2.0.0
         @angular-architects/module-federation: 13.0.1
         @angular/animations: 13.1.2
         @angular/cdk: 13.1.3
         @angular/common: 13.1.2
         @angular/compiler: 13.1.2
         @angular/core: 13.1.2
         @angular/forms: 13.1.2
         @angular/material: 13.2.5
         @angular/platform-browser: 13.1.2
         @angular/platform-browser-dynamic: 13.1.2
         @angular/router: 13.1.2
         @ngrx/effects: 13.0.2
         @ngrx/entity: 13.0.2
         @ngrx/router-store: 13.0.2
         @ngrx/store: 13.0.2
         @angular-devkit/build-angular: 13.1.3
         @angular/cli: 13.1.3
         @angular/compiler-cli: 13.1.2
         @angular/language-service: 13.1.2
         @nrwl/js: 13.4.5
         @storybook/angular: 6.4.22

**Comment by AgentEnder** [comment]
Hey @KL2808 , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

It looks like latest should be fine in your case, so I'd recommend trying `nx migrate latest`.

**Comment by KL2808** [comment]
Hi @AgentEnder, thanks for your quick response! I migrated to latest with ```nx migrate latest```, and it seems like the issue is fixed. The steps mentioned above are not reproducing the issue anymore. The projectBuildConfig is no longer missing after generating a storybook. Thank you! 🚀  

## Environment

   Node : 14.18.3
   OS   : win32 x64
   npm  : 6.14.15

   nx : 14.0.2
   @nrwl/angular : 14.0.2
   @nrwl/cypress : 14.0.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.2
   @nrwl/eslint-plugin-nx : 14.0.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.2
   @nrwl/js : 14.0.2
   @nrwl/linter : 14.0.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.0.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.2
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.2
   typescript : 4.6.3
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 13.0.2
         @ngrx/entity: 13.0.2
         @ngrx/router-store: 13.0.2
         @ngrx/store: 13.0.2
         @storybook/angular: 6.4.22

**Comment by KL2808** [comment]
Hi @AgentEnder, thanks for your quick response! I migrated to latest with ```nx migrate latest```, and it seems like the issue is fixed. The steps mentioned above are not reproducing the issue anymore. The projectBuildConfig is no longer missing after generating a storybook. Thank you! 🚀  

## Environment

   Node : 14.18.3
   OS   : win32 x64
   npm  : 6.14.15

   nx : 14.0.2
   @nrwl/angular : 14.0.2
   @nrwl/cypress : 14.0.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.2
   @nrwl/eslint-plugin-nx : 14.0.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.2
   @nrwl/js : 14.0.2
   @nrwl/linter : 14.0.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.0.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.2
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.2
   typescript : 4.6.3
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 13.0.2
         @ngrx/entity: 13.0.2
         @ngrx/router-store: 13.0.2
         @ngrx/store: 13.0.2
         @storybook/angular: 6.4.22
