### ISSUE TITLE
React Native - react-navigation/material-top-tabs crashing

### ISSUE THREAD

**Issue by sahil-republic** [nrwl/nx#9945]
## Current Behavior
When I am trying to the use the top tab bar navigation library in react native, it crashes with an error

## Expected Behavior

I am using the v6 of the react-navigation library, I have already installed the dependencies and requirement.

## Steps to Reproduce

You can reproduce this by installing the library in a react native nx workspace

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

Check the render method of `AnimatedComponent`. 

### Environment

Node : 16.14.2
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 13.9.3
   @nrwl/angular : undefined
   @nrwl/cypress : 13.8.8
   @nrwl/detox : 13.8.8
   @nrwl/devkit : 13.8.8
   @nrwl/eslint-plugin-nx : 13.8.8
   @nrwl/express : undefined
   @nrwl/jest : 13.8.8
   @nrwl/js : 13.8.8
   @nrwl/linter : 13.8.8
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.6
   @nrwl/nx-plugin : undefined
   @nrwl/react : 13.8.8
   @nrwl/react-native : 13.8.8
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.8
   @nrwl/web : 13.8.8
   @nrwl/workspace : 13.9.3
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by AgentEnder** [comment]
@sahil-republic can you put together a reproduction for us to look at? Thanks!
