### ISSUE TITLE
cypress setup not copying fixtures files

### ISSUE THREAD

**Issue by paesku** [nrwl/nx#996]
We recently updated from @nrwl/nx and related dependencies from 7.0.2 to 7.2.0.

When running e2e test with cypress, the fixture folder was not copied over to the corresponding output.

any ideas what changed in between? Angular versions are at 7.1.4.

**Comment by skorunka** [comment]
I have the same issue, which is blocking us from upgrading ``"@nrwl/builders": "7.0.2" to anything newer. The version 7.0.2 works correctly.

**Comment by paesku** [comment]
I'd like to mention, that when I move support code outside the support folder, the copy process completely messes up.

Example:

```
// top level
- apps
   --app-1
   --app-1-e2e
      --src
         --fixtures
         --integration
         --plugins
         --support
             app.po.ts // this file is importing and exporting code from foo.po.ts
   --po
     foo.po.ts 
```

Then the out-tsc will completely pull out the fixtures folder from the src folder and will look like this:

```
// out-tsc
- apps
   --app-1-e2e
      --src
         --app-1-e2e
            --src
               --integration
               --plugins
               --support
         --fixtures
         --po 
            foo.po.ts 
```

**Comment by Need-To-Learn** [comment]
Hi @skorunka
I added "fixtures" key, for you it would look like:
```json
{
  "fixtures": "../../../dist/out-tsc/apps/el/portal-e2e/src/fixtures"
}
```

**Comment by juristr** [comment]
@Need-To-Learn 🤔 I just upgraded to the latest version of NX...but for some reason the entire fixtures folder is not copied over ot the dist folder that's specified in the `cypress.json`. All other stuff is there, but not the fixtures. Which obviously results in a broken test when trying to access those

**Comment by skorunka** [comment]
@Need-To-Learn Hi, it works. IMHO this is a bug in `nrwl/builders` package.

**Comment by paesku** [comment]
I agree with @skorunka that if the behavior changed between the versions, it should be treated as a bug.
I expect the same behavior with the latest version as in the previous, without manually wiring up the output path.

**Comment by FrozenPandaz** [comment]
So, this line should check `fixturesFolder` instead of `fixtures`.

https://docs.cypress.io/guides/references/configuration.html#Folders-Files

https://github.com/nrwl/nx/blob/master/packages/builders/src/cypress/cypress.builder.ts#L158

**Comment by skorunka** [comment]
Good stuff. Thnx.
