### ISSUE TITLE
Cannot find module '../../jest.preset' on nx migrate latest

### ISSUE THREAD

**Issue by justinhandley** [nrwl/nx#9973]
## Current Behavior

When running nx migrate latest to version 14.02 I get

Running migration update-jest-config-extensions
Cannot find module '../../jest.preset'

But it doesn't specify where it can't find it - I searched all instances of that and the all correctly pointed to a jest preset file in root.

## Expected Behavior

One the migration, I expect it to work or give more useful feedback.

## Steps to Reproduce

Just run nx migrate latest - but obviously the entire project structure isn't easy to replicate.

### Failure Logs

Running migration update-jest-config-extensions
Cannot find module '../../jest.preset'
Require stack:
- /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/jest/src/utils/config/functions.js
- /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/jest/src/utils/config/update-config.js
- /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/jest/index.js
- /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/workspace/src/generators/library/library.js
- /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/workspace/index.js
- /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/angular/src/migrations/update-13-2-0/update-testing-imports.js
- /private/var/folders/_4/fklvk31d4vx19g5pv24v9_6m0000gn/T/tmp-16188-69NU7hEDsV0X/node_modules/nx/src/command-line/migrate.js
- /private/var/folders/_4/fklvk31d4vx19g5pv24v9_6m0000gn/T/tmp-16188-69NU7hEDsV0X/node_modules/nx/src/command-line/nx-commands.js
- /private/var/folders/_4/fklvk31d4vx19g5pv24v9_6m0000gn/T/tmp-16188-69NU7hEDsV0X/node_modules/nx/bin/init-local.js
- /private/var/folders/_4/fklvk31d4vx19g5pv24v9_6m0000gn/T/tmp-16188-69NU7hEDsV0X/node_modules/nx/bin/nx.js

### Environment

  NX   Report complete - copy this into the issue template

   Node : 16.10.0
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 14.0.2
   @nrwl/angular : 14.0.2
   @nrwl/cypress : 14.0.2
   @nrwl/detox : 14.0.2
   @nrwl/devkit : 14.0.2
   @nrwl/eslint-plugin-nx : 14.0.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.2
   @nrwl/js : 14.0.2
   @nrwl/linter : 14.0.2
   @nrwl/nest : 14.0.2
   @nrwl/next : Not Found
   @nrwl/node : 14.0.2
   @nrwl/nx-cloud : 13.3.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.0.2
   @nrwl/react-native : 14.0.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.2
   @nrwl/web : 14.0.2
   @nrwl/workspace : 14.0.2
   typescript : 4.6.3
   rxjs : 6.5.5
   ---------------------------------------
   Community plugins:
         @nxpm/stack: 4.18.0

**Comment by chrislambe** [comment]
Very similar issue here, but the error is about `jest.config` instead of `jest.preset`:

```
Running migration update-jest-config-extensions
Cannot find module './jest.config'
Require stack:
- /path/to/project/node_modules/@nrwl/jest/src/utils/config/functions.js
- /path/to/project/node_modules/@nrwl/jest/src/migrations/update-14-0-0/update-jest-config-ext.js
- /private/var/folders/mb/cvyzfj3d7h73dtph7777yxqw0000gn/T/tmp-52964-pNxeFyaS3YIc/node_modules/nx/src/command-line/migrate.js
- /private/var/folders/mb/cvyzfj3d7h73dtph7777yxqw0000gn/T/tmp-52964-pNxeFyaS3YIc/node_modules/nx/src/command-line/nx-commands.js
- /private/var/folders/mb/cvyzfj3d7h73dtph7777yxqw0000gn/T/tmp-52964-pNxeFyaS3YIc/node_modules/nx/bin/init-local.js
- /private/var/folders/mb/cvyzfj3d7h73dtph7777yxqw0000gn/T/tmp-52964-pNxeFyaS3YIc/node_modules/nx/bin/nx.js
```

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin arm64
   yarn : 3.1.0

   nx : 14.0.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.3
   @nrwl/eslint-plugin-nx : 14.0.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.3
   @nrwl/js : 14.0.3
   @nrwl/linter : 14.0.3
   @nrwl/nest : 14.0.3
   @nrwl/next : Not Found
   @nrwl/node : 14.0.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.3
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:

**Comment by barbados-clemens** [comment]
@chrislambe @justinhandley 
are those files being imported into your a project jest.config.js?

it looks to be related to how the migration updates the preset and so it requires reading your jest.config.js through `runInContext` call. 

I'm updating this migration to not do this anymore as we actually don't need to update the preset property in the configs anymore. 

this change is going to be a part of the change to `module.exports` => `export default` I'm working on. I was hoping to get something in draft today but ran into issues with updating tests to validate the new behavior. I hope to have something end of this week/early next week ready to be merged.

**Comment by viceice** [comment]
Can i simply manually do the migration? if i'm correct it only renames files from js to ts extension?

**Comment by justinhandley** [comment]
So, for me it was that I was running react-native and the upgrade to 13 changed this

const workspacePreset = require('../../jest.preset')
module.exports = {
  ...workspacePreset,
  displayName: 'native',
  preset: 'react-native',
  moduleFileExtensions: ['ts', 'js', 'html', 'tsx', 'jsx'],
  setupFilesAfterEnv: ['<rootDir>/test-setup.ts'],
  transform: {
    '\\.(js|ts|tsx)$': require.resolve('react-native/jest/preprocessor.js'),
    '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$': require.resolve('react-native/jest/assetFileTransformer.js'),
  },
}

to no longer use workspacePreset, but instead to use   resolver: '@nrwl/jest/plugins/resolver',

But, the migration didn't remove the require at the top.  I took that out and ran it again and it was fine.
