### ISSUE TITLE
How to add new dependency to shared config?

### ISSUE THREAD

**Issue by dkhrunov** [nrwl/nx#9978]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Module-federation overriding shared library config](https://nx.dev/module-federation/faster-builds#overriding-shared-library-config)

### Additional context or description

Not covered case, when user need to add new dependency to shared config.
How it we can do with new function in Nx v13 `withModuleFederation`?

**Comment by Coly010** [comment]
It should be covered in the docs.

The dependencies get shared automatically by Nx. You no longer need to specifically state which dependencies need to be shared.

You can see it here in the docs already.

![A1648ACD-F8B7-4AFE-96DD-E0ED29DB18BB](https://user-images.githubusercontent.com/12140467/165155350-98f977c0-d8ad-4e16-b44a-721f34109d4c.jpeg)

**Comment by a616101** [comment]
@angular/anumations  does not appear in the shared list.

is it excluded?

**Comment by dkhrunov** [comment]
> It should be covered in the docs.

Thanks

**Comment by a616101** [comment]
> It should be covered in the docs.
> 
> The dependencies get shared automatically by Nx. You no longer need to specifically state which dependencies need to be shared.
> 
> You can see it here in the docs already.
> 
> ![A1648ACD-F8B7-4AFE-96DD-E0ED29DB18BB](https://user-images.githubusercontent.com/12140467/165155350-98f977c0-d8ad-4e16-b44a-721f34109d4c.jpeg)

@angular/anumations  does not appear in the shared list.

is it excluded?
