### ISSUE TITLE
Fail immediately when run-many in parellel

### ISSUE THREAD

**Issue by msyesyan** [nrwl/nx#9980]
when I have many subjects and run `nx run-many target=build --all --parellel`, can we just fail immediately when one of the sub project failed?

**Comment by AgentEnder** [comment]
With run-many it is generally helpful to know which projects fail, so if we were to stop as soon as one failed then we would miss out on that info.

Imagine running `nx run-many --all test`. If `project-a` and `project-b` would both have failing tests, it'd be paramount that developers know both of them have broken.
