### ISSUE TITLE
support yaml format

### ISSUE THREAD

**Issue by airtonix** [nrwl/nx#9983]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
`nx.json`, `workspace.json`, `project.json` should all have supported yaml formats too: 

`nx.yaml`, `workspace.yaml`, `project.yaml`.

## Motivation
- comments aren't a thing in `.json`
- multiline strings aren't a thing in `.json`

## Suggested Implementation
- conslidate the access to all the above files through a single loader function that looks for either `.json` then `.yaml` variants
- when `.yaml` variant is discovered, load it using https://www.npmjs.com/package/yaml

meh.

**Comment by VincentThomas06** [comment]
This would be really nice for a better, cleaner config!

**Comment by jase88** [comment]
I don't want to dispute the feature proposal, but wouldn't the motivation points also be met with json5?

**Comment by airtonix** [comment]
> I don't want to dispute the feature proposal, but wouldn't the motivation points also be met with json5?

ok then:

> conslidate the access to all the above files through a single loader function that looks for either `.json`, `.json5` then `.yaml` variants

**Comment by jase88** [comment]
Related issue: 
https://github.com/nrwl/nx/issues/4244

**Comment by milahu** [comment]
please feel free to continue my draft in #13459

**Comment by FrozenPandaz** [comment]
We understand that comments would indeed be useful in nx.json.

Unfortunately, we are not interested in fracturing the config used by consumers currently to include yaml as a format. You can add blank properties in the nx.json with comments as follows:

{
  "//": "namedInputs are filesets used to define files to be considered when creating a hash for a task",
  "namedInputs": {}
}
