### ISSUE TITLE
Workspace generator cannot run because it uses the wrong TypeScript compiler cli with pnpm v7

### ISSUE THREAD

**Issue by muuvmuuv** [nrwl/nx#9989]
## Current Behavior

Running `pnpm nx workspace-generator ... ...` always results in "This is not the tsc command you are looking for" because in case of *pnpm v7* "pnpx" acts like "pnpm dlx" and fetches tsc from npm which does not respect the locally installed "typescript" package. This part here seems to be broken, where v7 is never "true". It would make much more sense to use the "semver" package to validate the version range or some more enhanced if-clause ^^.

> https://github.com/nrwl/nx/blob/f7369f5948db7a59ff1b8d34bc43318130ab5dac/packages/nx/src/utils/package-manager.ts#L66-L68

## Expected Behavior

Use package manager execution that prefers locally installed binaries instead of fetching them.

## Steps to Reproduce

Use latest pnpm rc version and run a workspace generator/tool.

**Comment by AgentEnder** [comment]
We should definitely use semver to match up against a range. Since you've already identified the problem code, would you like to take a shot at this one?

**Comment by muuvmuuv** [comment]
Sure. Any other locations where version checks are being made that I can also patch?

**Comment by muuvmuuv** [comment]
@AgentEnder `semver` was already included. I wonder why it wasn't used by @jmcdo29 in first place. Maybe you can both review in case it was intended.
