### ISSUE TITLE
When trying to use any ionic plugin getting errors

### ISSUE THREAD

**Issue by gouthamcs12** [nrwl/nx#9999]
### Discussed in https://github.com/nrwl/nx/discussions/9991

<div type='discussions-op-text'>

<sup>Originally posted by **gouthamcs12** April 25, 2022</sup>
Hi Team
I am trying to use nxtend/ionic-angular in my project, But I got stuck while using plugins
1st use case : need to get a current app version
So I have installed these dependencies
   1)npm install cordova-plugin-app-version 2) npm install @awesome-cordova-plugins/app-version when I tried to run in android 
     studio emulator getting bellow error
<img width="943" alt="Capture3" src="https://user-images.githubusercontent.com/57672192/165129208-69471a24-a6c8-4272-b91c-4cdf7863ef99.PNG">

2nd use case need to use camera plugin
       similar issue for camera plugin
<img width="947" alt="Capture1" src="https://user-images.githubusercontent.com/57672192/165129338-7749a5d3-cd35-46f9-b834-f87d48c32dd6.PNG">

nx report 
<img width="483" alt="Capture2" src="https://user-images.githubusercontent.com/57672192/165129402-bcf643ac-b48f-4de6-b57e-23c130df2092.PNG">

package.json
{
  "name": "matchlinkers-portal",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^12.2.0",
    "@angular/common": "^12.2.0",
    "@angular/compiler": "^12.2.0",
    "@angular/core": "^12.2.0",
    "@angular/forms": "^12.2.0",
    "@angular/platform-browser": "^12.2.0",
    "@angular/platform-browser-dynamic": "^12.2.0",
    "@angular/router": "^12.2.0",
    "@awesome-cordova-plugins/app-version": "^5.41.0",
    "@capacitor/camera": "^1.3.1",
    "@capacitor/core": "^3.2.5",
    "@capacitor/filesystem": "^1.1.0",
    "@capacitor/storage": "^1.2.5",
    "@ionic/angular": "^5.8.3",
    "@ionic/pwa-elements": "^3.1.1",
    "@nrwl/angular": "13.0.0",
    "@nxtend/ionic-angular": "^13.1.0",
    "cordova-plugin-app-version": "^0.1.14",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.0",
    "@angular-eslint/eslint-plugin": "~12.3.0",
    "@angular-eslint/eslint-plugin-template": "~12.3.0",
    "@angular-eslint/template-parser": "~12.3.0",
    "@angular/cli": "~12.2.0",
    "@angular/compiler-cli": "^12.2.0",
    "@angular/language-service": "^12.2.0",
    "@capacitor/android": "^3.2.5",
    "@capacitor/cli": "^3.2.5",
    "@capacitor/ios": "^3.2.5",
    "@nrwl/angular": "^13.0.0",
    "@nrwl/cli": "13.0.0",
    "@nrwl/cypress": "13.0.0",
    "@nrwl/eslint-plugin-nx": "13.0.0",
    "@nrwl/jest": "13.0.0",
    "@nrwl/linter": "13.0.0",
    "@nrwl/tao": "13.0.0",
    "@nrwl/workspace": "13.0.0",
    "@nxtend/capacitor": "^13.0.0",
    "@types/jest": "27.0.2",
    "@types/node": "14.14.33",
    "@typescript-eslint/eslint-plugin": "~4.33.0",
    "@typescript-eslint/parser": "~4.33.0",
    "cypress": "^8.3.0",
    "eslint": "7.32.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "27.2.3",
    "jest-preset-angular": "10.0.1",
    "prettier": "^2.3.1",
    "ts-jest": "27.0.5",
    "typescript": "~4.3.5"
  }
}

github link [https://github.com/gouthamcs12/nx-ionic](url)
</div>

**Comment by AgentEnder** [comment]
Hey @gouthamcs12, I'm going to close out this issue since it occurs when using a community plugin and is directly related to its executors.

You'll need to report this issue to them, and they will be able to assist with such issues. This repo's issues only cover the packages that start with '@nrwl' or the 'nx' package itself.
